./tools/openblas_support.py:45:    assert plat in SUPPORTED_PLATFORMS,  f'invalid platform {plat}'
./tools/openblas_support.py:64:    assert ret in ('1', '2010', '2014', '_2_24'), f'invalid MB_ML_VER {ret}'
./tools/openblas_support.py:315:    assert check_str in res, f'{expected_version} not found in {res}'
./tools/openblas_support.py:317:        assert b"USE64BITINT" in res
./tools/openblas_support.py:319:        assert b"USE64BITINT" not in res
./tools/refguide_check.py:1202:                assert isinstance(v, tuple), v
./tools/cythonize.py:58:    assert fromfile.endswith('.pyx.in')
./tools/cythonize.py:71:    assert fromfile.endswith('.pxd.in')
./tools/cythonize.py:72:    assert tofile.endswith('.pxd')
./tools/cythonize.py:82:    assert fromfile.endswith('.pxi.in')
./tools/cythonize.py:83:    assert tofile.endswith('.pxi')
./tools/cythonize.py:93:    assert fromfile.endswith('.pxd.in')
./tools/cythonize.py:94:    assert tofile.endswith('.pxd')
./tools/npy_tempita/__init__.py:114:            assert len(delimiters) == 2 and all(
./tools/npy_tempita/__init__.py:270:            assert 0, "Unknown code: %r" % name
./tools/npy_tempita/__init__.py:295:            assert not isinstance(part, basestring_)
./tools/npy_tempita/__init__.py:925:        assert 0, "Unexpected token %r at %s" % (first, pos)
./tools/npy_tempita/__init__.py:944:    assert first.startswith('for ')
./tools/npy_tempita/__init__.py:975:    assert first.startswith('default ')
./tools/npy_tempita/__init__.py:997:    assert first.startswith('inherit ')
./tools/npy_tempita/__init__.py:1005:    assert first.startswith('def ')
./numpy/distutils/unixccompiler.py:137:        log.debug("skipping %s (up-to-date)", output_filename)
./numpy/distutils/ccompiler.py:774:    log.debug('new_compiler returns %s' % (klass))
./numpy/distutils/misc_util.py:144:        assert apath[len(pd)] in [os.sep], repr((path, apath[len(pd)]))
./numpy/distutils/misc_util.py:192:            assert is_string(p)
./numpy/distutils/misc_util.py:267:    assert is_sequence(paths), repr(type(paths))
./numpy/distutils/misc_util.py:269:    assert not is_string(paths), repr(paths)
./numpy/distutils/misc_util.py:1000:        assert '*' not in subpackage_name, repr((subpackage_name, subpackage_path, parent_name))
./numpy/distutils/misc_util.py:1063:            assert isinstance(d, dict), repr(type(d))
./numpy/distutils/misc_util.py:1170:                            assert s==path_list[i], repr((s, path_list[i], data_path, d, path, rpath))
./numpy/distutils/misc_util.py:1182:        assert not is_glob_pattern(d), repr(d)
./numpy/distutils/misc_util.py:1296:        assert len(files)==1
./numpy/distutils/misc_util.py:1345:        assert not is_glob_pattern(d), repr((d, filepat))
./numpy/distutils/misc_util.py:1504:                assert isinstance(info, dict), repr(info)
./numpy/distutils/misc_util.py:1884:            assert isinstance(extlib, Extension), repr(extlib)
./numpy/distutils/system_info.py:737:        assert isinstance(self.search_static_first, int)
./numpy/distutils/system_info.py:924:        log.debug('( %s = %s )', key, ':'.join(ret))
./numpy/distutils/system_info.py:1010:        assert is_string(lib_dir)
./numpy/distutils/system_info.py:1023:                assert len(p) == 1
./numpy/distutils/system_info.py:3099:    log.debug('(paths: %s)', ','.join(result))
./numpy/distutils/exec_command.py:113:        assert os.path.isfile(pythonexe), '%r is not a file' % (pythonexe,)
./numpy/distutils/exec_command.py:126:    log.debug('find_executable(%r)' % exe)
./numpy/distutils/exec_command.py:168:    log.debug('_preserve_environment(%r)' % (names))
./numpy/distutils/exec_command.py:173:    log.debug('_update_environment(...)')
./numpy/distutils/exec_command.py:211:    log.debug('exec_command(%r,%s)' % (command,
./numpy/distutils/exec_command.py:232:        log.debug('New cwd: %s' % execute_in)
./numpy/distutils/exec_command.py:234:        log.debug('Retaining cwd: %s' % oldcwd)
./numpy/distutils/exec_command.py:247:            log.debug('Restored cwd to %s' % oldcwd)
./numpy/distutils/mingw32ccompiler.py:300:        log.debug('Skip building import library: '
./numpy/distutils/mingw32ccompiler.py:306:        log.debug('Skip building msvcr library:'
./numpy/distutils/mingw32ccompiler.py:318:        log.debug('Skip building msvcr library: "%s" exists' %
./numpy/distutils/mingw32ccompiler.py:399:        log.debug('Skip building import library: "%s" exists', out_file)
./numpy/distutils/mingw32ccompiler.py:421:        log.debug('Skip building import library: "%s" exists', out_file)
./numpy/distutils/fcompiler/gnu.py:255:        assert "," not in dir
./numpy/distutils/fcompiler/intel.py:25:        assert "," not in dir
./numpy/distutils/fcompiler/__init__.py:245:            assert self._is_customised
./numpy/distutils/fcompiler/__init__.py:272:        assert value is None or is_sequence_of_strings(value[1:]), (key, value)
./numpy/distutils/fcompiler/__init__.py:294:        assert self._is_customised
./numpy/distutils/fcompiler/__init__.py:423:        assert self._is_customised
./numpy/distutils/fcompiler/__init__.py:592:        assert self.compile_switch.strip()
./numpy/distutils/fcompiler/__init__.py:683:            log.debug("skipping %s (up-to-date)", output_filename)
./numpy/distutils/fcompiler/__init__.py:821:            log.debug("_find_existing_fcompiler: compiler_type='%s' raised DistutilsModuleError", compiler_type)
./numpy/distutils/fcompiler/__init__.py:823:            log.debug("_find_existing_fcompiler: compiler_type='%s' not found", compiler_type)
./numpy/distutils/fcompiler/__init__.py:931:            log.debug("show_fcompilers: %s not found" % (compiler,))
./numpy/distutils/fcompiler/__init__.py:932:            log.debug(repr(e))
./numpy/distutils/command/build_ext.py:387:            log.debug("Detected changes on compiler optimizations")
./numpy/distutils/command/build_ext.py:390:            log.debug("skipping '%s' extension (up-to-date)", ext.name)
./numpy/distutils/command/build_src.py:490:                    log.debug('  source %s does not exist: skipping f2py\'ing.' \
./numpy/distutils/command/build_src.py:546:                log.debug("  skipping '%s' f2py interface (up-to-date)" % (source))
./numpy/distutils/command/build_src.py:566:                log.debug("  skipping f2py fortran files for '%s' (up-to-date)"\
./numpy/distutils/command/build_src.py:713:                log.debug("  skipping '%s' swig interface (up-to-date)" \
./numpy/distutils/command/__init__.py:11:        assert_raises(AttributeError, delattr, a, s)
./numpy/distutils/command/build_clib.py:247:            log.debug("Detected changes on compiler optimizations")
./numpy/distutils/command/build_clib.py:250:            log.debug("skipping '%s' library (up-to-date)", lib_name)
./numpy/distutils/_shell_utils.py:68:        assert not ctypes.windll.kernel32.LocalFree(lpargs)
./numpy/distutils/_shell_utils.py:71:        assert args[0] == "dummy"
./numpy/distutils/ccompiler_opt.py:601:        assert(isinstance(sources, list))
./numpy/distutils/ccompiler_opt.py:602:        assert(isinstance(flags, list))
./numpy/distutils/ccompiler_opt.py:613:        assert(isinstance(source, str))
./numpy/distutils/ccompiler_opt.py:1053:                assert(isinstance(flags, str))
./numpy/distutils/ccompiler_opt.py:1066:        assert(isinstance(flags, list))
./numpy/distutils/ccompiler_opt.py:1097:        assert(isinstance(flags, list))
./numpy/distutils/ccompiler_opt.py:1254:        assert(
./numpy/distutils/ccompiler_opt.py:1260:        assert(force_flags is None or isinstance(force_flags, list))
./numpy/distutils/ccompiler_opt.py:1281:        assert(name.isupper())
./numpy/distutils/ccompiler_opt.py:1351:            assert(hasattr(names, "__iter__"))
./numpy/distutils/ccompiler_opt.py:1393:        assert(
./numpy/distutils/ccompiler_opt.py:1427:        assert(
./numpy/distutils/ccompiler_opt.py:1558:        assert(name.isupper())
./numpy/distutils/ccompiler_opt.py:1559:        assert(force_flags is None or isinstance(force_flags, list))
./numpy/distutils/ccompiler_opt.py:1575:        assert(isinstance(name, str))
./numpy/distutils/ccompiler_opt.py:1596:        assert isinstance(name, str)
./numpy/distutils/ccompiler_opt.py:1646:        assert(feature_name.isupper())
./numpy/distutils/ccompiler_opt.py:1648:        assert(feature is not None)
./numpy/distutils/ccompiler_opt.py:1915:        assert(isinstance(tokens, str))
./numpy/distutils/ccompiler_opt.py:2511:        assert(isinstance(target, (str, tuple)))
./numpy/core/overrides.py:119:        assert example.__module__ == 'numpy'
./numpy/core/code_generators/generate_umath.py:86:        assert len(self.in_) == nin
./numpy/core/code_generators/generate_umath.py:89:        assert len(self.out) == nout
./numpy/core/code_generators/ufunc_docstrings.py:53:            assert '$OUT_SCALAR_1' in doc, "in {}".format(name)
./numpy/core/code_generators/ufunc_docstrings.py:55:            assert '$OUT_SCALAR_2' in doc, "in {}".format(name)
./numpy/core/code_generators/ufunc_docstrings.py:57:            assert False, "Could not detect number of inputs in {}".format(name)
./numpy/core/numeric.py:1645:            assert b.shape[-1] == 3
./numpy/core/numeric.py:1655:        assert a.shape[-1] == 3
./numpy/core/numeric.py:1670:            assert b.shape[-1] == 2
./numpy/core/_exceptions.py:27:    assert issubclass(cls, Exception)
./numpy/core/_exceptions.py:44:        assert len(self.dtypes) == 2
./numpy/core/arrayprint.py:354:    ...      assert_equal(opts, np.get_printoptions())
./numpy/core/src/multiarray/arrayfunction_override.c:16:    assert(method != NULL);
./numpy/core/src/multiarray/arrayfunction_override.c:415:        assert(args == NULL);
./numpy/core/src/multiarray/arrayfunction_override.c:416:        assert(kwargs == NULL);
./numpy/core/src/multiarray/common.c:212:        assert(!PyArray_CHKFLAGS(ap, NPY_ARRAY_OWNDATA));
./numpy/core/src/multiarray/item_selection.c:1666:        assert(N > 0);  /* Guaranteed and assumed by indbuffer */
./numpy/core/src/multiarray/item_selection.c:2344:    assert(elsize <= 8);
./numpy/core/src/multiarray/buffer.c:150:        assert(offset == 0);
./numpy/core/src/multiarray/buffer.c:152:            assert(descr->elsize % descr->alignment == 0);
./numpy/core/src/multiarray/buffer.c:407:            assert(descr->elsize % 4 == 0);
./numpy/core/src/multiarray/buffer.c:480:        assert(PyArray_Check(obj));
./numpy/core/src/multiarray/buffer.c:498:            assert((size_t)info->shape % sizeof(npy_intp) == 0);
./numpy/core/src/multiarray/multiarraymodule.c:446:        assert(dtype == NULL);
./numpy/core/src/multiarray/multiarraymodule.c:491:        assert(PyArray_DESCR(ret) == descr);
./numpy/core/src/multiarray/multiarraymodule.c:561:        assert(dtype == NULL);
./numpy/core/src/multiarray/multiarraymodule.c:596:        assert(PyArray_DESCR(ret) == descr);
./numpy/core/src/multiarray/nditer_api.c:2051:                assert(0);
./numpy/core/src/multiarray/nditer_api.c:2230:                assert(!(op_itflags[iop] & NPY_OP_ITFLAG_USINGBUFFER));
./numpy/core/src/multiarray/nditer_api.c:2243:                assert(!(op_itflags[iop] & NPY_OP_ITFLAG_USINGBUFFER));
./numpy/core/src/multiarray/abstractdtypes.c:26:    assert(PyLong_Check(obj));
./numpy/core/src/multiarray/abstractdtypes.c:65:    assert(PyFloat_CheckExact(obj));
./numpy/core/src/multiarray/abstractdtypes.c:79:    assert(PyComplex_CheckExact(obj));
./numpy/core/src/multiarray/abstractdtypes.c:221:            assert(other->type_num == NPY_LONGDOUBLE);
./numpy/core/src/multiarray/iterators.c:1762:            assert(PyArray_EquivArrTypes(x->ao, fill) == NPY_TRUE);
./numpy/core/src/multiarray/refcount.c:78:        assert(0);
./numpy/core/src/multiarray/refcount.c:140:        assert(0);
./numpy/core/src/multiarray/refcount.c:351:        assert(0);
./numpy/core/src/multiarray/dragon4.c:42:#define DEBUG_ASSERT(stmnt) assert(stmnt)
./numpy/core/src/multiarray/dragon4.c:44:#define DEBUG_ASSERT(stmnt) do {} while(0)
./numpy/core/src/multiarray/dragon4.c:367:        DEBUG_ASSERT(carry == 1);
./numpy/core/src/multiarray/dragon4.c:368:        DEBUG_ASSERT((npy_uint32)(resultCur - result->blocks) ==
./numpy/core/src/multiarray/dragon4.c:390:    DEBUG_ASSERT(result != lhs && result != rhs);
./numpy/core/src/multiarray/dragon4.c:404:    DEBUG_ASSERT(maxResultLen <= c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:434:            DEBUG_ASSERT(resultCur < result->blocks + maxResultLen);
./numpy/core/src/multiarray/dragon4.c:466:        DEBUG_ASSERT(lhs->length + 1 <= c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:493:        DEBUG_ASSERT(in->length + 1 <= c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:519:        DEBUG_ASSERT(result->length + 1 <= c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:542:        DEBUG_ASSERT(result->length + 1 <= c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:768:    DEBUG_ASSERT(exponent < 8192);
./numpy/core/src/multiarray/dragon4.c:816:    DEBUG_ASSERT(exponent < 8192);
./numpy/core/src/multiarray/dragon4.c:870:    DEBUG_ASSERT(blockIdx < c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:909:    DEBUG_ASSERT(!divisor->length == 0 &&
./numpy/core/src/multiarray/dragon4.c:931:    DEBUG_ASSERT(quotient <= 9);
./numpy/core/src/multiarray/dragon4.c:1012:    DEBUG_ASSERT(inLength + shiftBlocks < c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:1013:    DEBUG_ASSERT(shift != 0);
./numpy/core/src/multiarray/dragon4.c:1047:        DEBUG_ASSERT(outBlockIdx < c_BigInt_MaxBlocks);
./numpy/core/src/multiarray/dragon4.c:1062:        DEBUG_ASSERT(outBlockIdx == shiftBlocks + 1);
./numpy/core/src/multiarray/dragon4.c:1183:    DEBUG_ASSERT(bufferSize > 0);
./numpy/core/src/multiarray/dragon4.c:1406:    DEBUG_ASSERT(scale->length > 0);
./numpy/core/src/multiarray/dragon4.c:1422:        DEBUG_ASSERT(hiBlockLog2 < 3 || hiBlockLog2 > 27);
./numpy/core/src/multiarray/dragon4.c:1448:            DEBUG_ASSERT(outputDigit < 10);
./numpy/core/src/multiarray/dragon4.c:1494:            DEBUG_ASSERT(outputDigit < 10);
./numpy/core/src/multiarray/dragon4.c:1574:    DEBUG_ASSERT(outputLen <= bufferSize);
./numpy/core/src/multiarray/dragon4.c:1656:    DEBUG_ASSERT(bufferSize > 0);
./numpy/core/src/multiarray/dragon4.c:1659:        DEBUG_ASSERT(precision >= 0);
./numpy/core/src/multiarray/dragon4.c:1676:    DEBUG_ASSERT(numDigits > 0);
./numpy/core/src/multiarray/dragon4.c:1677:    DEBUG_ASSERT(numDigits <= bufferSize);
./numpy/core/src/multiarray/dragon4.c:1862:    DEBUG_ASSERT(pos <= maxPrintLen);
./numpy/core/src/multiarray/dragon4.c:1899:        DEBUG_ASSERT(precision >= 0);
./numpy/core/src/multiarray/dragon4.c:1902:    DEBUG_ASSERT(bufferSize > 0);
./numpy/core/src/multiarray/dragon4.c:1934:    DEBUG_ASSERT(numDigits > 0);
./numpy/core/src/multiarray/dragon4.c:1935:    DEBUG_ASSERT(numDigits <= bufferSize);
./numpy/core/src/multiarray/dragon4.c:2038:        DEBUG_ASSERT(printExponent < 100000);
./numpy/core/src/multiarray/dragon4.c:2065:    DEBUG_ASSERT(bufferSize > 0);
./numpy/core/src/multiarray/dragon4.c:2084:    DEBUG_ASSERT(bufferSize > 0);
./numpy/core/src/multiarray/dragon4.c:2118:    DEBUG_ASSERT(bufferSize > 0);
./numpy/core/src/multiarray/dragon4.c:3034:            DEBUG_ASSERT(exponent1 == -1022);
./numpy/core/src/multiarray/array_coercion.c:229:    assert(PyObject_TypeCheck(DType, (PyTypeObject *)&PyArrayDTypeMeta_Type));
./numpy/core/src/multiarray/array_coercion.c:523:                assert(i == 0);
./numpy/core/src/multiarray/array_coercion.c:618:    assert(!(*flags & DESCRIPTOR_WAS_SET));
./numpy/core/src/multiarray/array_coercion.c:725:        assert(DType->type_num != NPY_OBJECT);  /* not parametric */
./numpy/core/src/multiarray/array_coercion.c:1073:    assert(!PyBytes_Check(obj) && !PyUnicode_Check(obj));
./numpy/core/src/multiarray/array_coercion.c:1185:    assert(*out_descr == NULL || fixed_DType == NULL);
./numpy/core/src/multiarray/array_coercion.c:1188:        assert(PyObject_TypeCheck(
./numpy/core/src/multiarray/array_coercion.c:1193:        assert(fixed_DType == NPY_DTYPE(requested_descr));
./numpy/core/src/multiarray/array_coercion.c:1304:                assert(PyArray_NDIM(arr) + current->depth >= ndim);
./numpy/core/src/multiarray/array_coercion.c:1372:        assert(*out_descr == requested_descr);
./numpy/core/src/multiarray/array_coercion.c:1451:            assert(dtype != (PyObject * )&PyArrayDescr_Type);  /* not np.dtype */
./numpy/core/src/multiarray/methods.c:1140:    assert(PyTuple_CheckExact(args));
./numpy/core/src/multiarray/methods.c:1141:    assert(kwds == NULL || PyDict_CheckExact(kwds));
./numpy/core/src/multiarray/dtypemeta.c:27:    assert(((PyTypeObject *)self)->tp_flags & Py_TPFLAGS_HEAPTYPE);
./numpy/core/src/multiarray/dtypemeta.c:93:    assert(0);
./numpy/core/src/multiarray/dtypemeta.c:94:    assert(!NPY_DT_is_legacy(type) && (PyTypeObject *)type != &PyArrayDescr_Type);
./numpy/core/src/multiarray/dtypemeta.c:131:    assert(!NPY_DT_is_parametric(cls));
./numpy/core/src/multiarray/dtypemeta.c:518:    assert(cls->type_num < NPY_NTYPES);
./numpy/core/src/multiarray/dtypemeta.c:545:    assert(cls->type_num < NPY_NTYPES && cls != other);
./numpy/core/src/multiarray/alloc.c:77:    assert((esz == 1 && cache == datacache) ||
./numpy/core/src/multiarray/alloc.c:79:    assert(PyGILState_Check());
./numpy/core/src/multiarray/alloc.c:114:    assert(PyGILState_Check());
./numpy/core/src/multiarray/alloc.c:263:    assert(size != 0);
./numpy/core/src/multiarray/alloc.c:327:    assert(size != 0);
./numpy/core/src/multiarray/alloc.c:425:    assert(size != 0);
./numpy/core/src/multiarray/alloc.c:494:    assert(size != 0);
./numpy/core/src/multiarray/common_dtype.c:120:    assert(length >= 2);
./numpy/core/src/multiarray/arrayobject.c:256:        assert(cache->converted_obj == src_object);
./numpy/core/src/multiarray/arrayobject.c:275:        assert (ndim <= PyArray_NDIM(dest));  /* would error during discovery */
./numpy/core/src/multiarray/arrayobject.c:1306:         *   assert np.array(l, dtype="S1") == np.array(l, dtype="O")
./numpy/core/src/multiarray/dtype_transfer.c:1121:    assert(PyDataType_ISNOTSWAPPED(src_dtype));
./numpy/core/src/multiarray/dtype_transfer.c:1210:    assert(src_dtype->type_num == NPY_UNICODE);
./numpy/core/src/multiarray/dtype_transfer.c:3030:    assert(PyArray_DescrCheck(cast_info->descriptors[0]));
./numpy/core/src/multiarray/dtype_transfer.c:3031:    assert(PyArray_DescrCheck(cast_info->descriptors[1]));
./numpy/core/src/multiarray/dtype_transfer.c:3064:    assert(cast_info->auxdata == NULL);
./numpy/core/src/multiarray/dtype_transfer.c:3160:            assert(castdata.from.func != NULL);
./numpy/core/src/multiarray/dtype_transfer.c:3199:            assert(castdata.to.func != NULL);
./numpy/core/src/multiarray/dtype_transfer.c:3261:    assert(src_dtype != NULL);
./numpy/core/src/multiarray/dtype_transfer.c:3273:        assert(move_references);
./numpy/core/src/multiarray/dtype_transfer.c:3517:    assert(dst_dtype != NULL);
./numpy/core/src/multiarray/dlpack.c:46:        assert(!PyErr_Occurred());
./numpy/core/src/multiarray/dlpack.c:73:        assert(!PyErr_Occurred());
./numpy/core/src/multiarray/nditer_constr.c:1984:            assert(i < orig_op_ndim);
./numpy/core/src/multiarray/nditer_constr.c:2574:                    assert(!reduction_axis || shape[i] == 1);
./numpy/core/src/multiarray/convert_datatype.c:421:        assert(casting != NPY_NO_CASTING);
./numpy/core/src/multiarray/convert_datatype.c:424:        assert(casting != NPY_EQUIV_CASTING
./numpy/core/src/multiarray/convert_datatype.c:1035:    assert(n > 0);  /* concatenate requires at least one array input. */
./numpy/core/src/multiarray/convert_datatype.c:1912:    assert(ndescr > 0);
./numpy/core/src/multiarray/convert_datatype.c:2318:    assert(loop_descrs[0]->elsize == loop_descrs[1]->elsize);
./numpy/core/src/multiarray/convert_datatype.c:2369:    assert(NPY_DT_is_legacy(dtypes[0]) && NPY_DT_is_legacy(dtypes[1]));
./numpy/core/src/multiarray/convert_datatype.c:2406:    assert(descrs[0]->kind == descrs[1]->kind);
./numpy/core/src/multiarray/convert_datatype.c:2407:    assert(descrs[0]->elsize == descrs[1]->elsize);
./numpy/core/src/multiarray/convert_datatype.c:2516:    assert(slots[1].pfunc && slots[2].pfunc && slots[3].pfunc && slots[4].pfunc);
./numpy/core/src/multiarray/convert_datatype.c:2609:            assert(given_descrs[0]->elsize <= 8);
./numpy/core/src/multiarray/convert_datatype.c:2610:            assert(given_descrs[0]->elsize > 0);
./numpy/core/src/multiarray/convert_datatype.c:2676:        assert(dtypes[0]->type_num == NPY_UNICODE &&
./numpy/core/src/multiarray/convert_datatype.c:2791:    assert(NPY_DTYPE(descrs[0]) == NPY_DTYPE(descrs[1]));
./numpy/core/src/multiarray/convert_datatype.c:3426:        assert(from_sub || to_sub);
./numpy/core/src/multiarray/descriptor.c:733:    assert(PyUnicode_Check(obj));
./numpy/core/src/multiarray/descriptor.c:1829:        assert(0);
./numpy/core/src/multiarray/descriptor.c:1962:    assert(PyTuple_Check(self->subarray->shape));
./numpy/core/src/multiarray/ctors.c:486:            assert(ndim != 0);  /* guaranteed by PyArray_AssignFromCache */
./numpy/core/src/multiarray/ctors.c:487:            assert(PyArray_NDIM(self) == 0);
./numpy/core/src/multiarray/ctors.c:497:            assert(0);
./numpy/core/src/multiarray/ctors.c:520:        assert(PyArray_Check(obj));
./numpy/core/src/multiarray/ctors.c:526:        assert(depth != ndim);
./numpy/core/src/multiarray/ctors.c:596:    assert(cache->sequence);
./numpy/core/src/multiarray/ctors.c:597:    assert(ndim != 0);  /* guaranteed if cache contains a sequence */
./numpy/core/src/multiarray/ctors.c:1696:            assert(PyArray_NDIM(ret) != ndim);
./numpy/core/src/multiarray/ctors.c:1749:        assert(cache->converted_obj == op);
./numpy/core/src/multiarray/ctors.c:1768:        assert(ndim == 0);
./numpy/core/src/multiarray/ctors.c:1791:        assert(ndim == 0);
./numpy/core/src/multiarray/ctors.c:1846:        assert(ndim == 0);
./numpy/core/src/multiarray/ctors.c:1856:    assert(ndim != 0);
./numpy/core/src/multiarray/ctors.c:1857:    assert(op == cache->converted_obj);
./numpy/core/src/multiarray/compiled_base.c:1188:    assert(order == NPY_CORDER || order == NPY_FORTRANORDER);
./numpy/core/src/multiarray/datetime.c:45:    assert(unit > 0);
./numpy/core/src/multiarray/datetime.c:52:    assert(mod >= 0);
./numpy/core/src/multiarray/datetime.c:59:    assert(unit > 0);
./numpy/core/src/multiarray/datetime.c:66:    assert(mod >= 0);
./numpy/core/src/multiarray/datetime.c:568:                assert(out->hour >= 0);
./numpy/core/src/multiarray/datetime.c:587:                assert(out->sec >= 0);
./numpy/core/src/multiarray/datetime.c:2951:            assert(NPY_FALSE);
./numpy/core/src/multiarray/datetime.c:3368:        assert(type_nums[0] == NPY_TIMEDELTA);
./numpy/core/src/multiarray/datetime.c:3784:    assert(meta1 != NULL);
./numpy/core/src/multiarray/datetime.c:3786:    assert(meta2 != NULL);
./numpy/core/src/multiarray/datetime.c:3896:    assert(needs_api == 0);
./numpy/core/src/multiarray/datetime.c:3915:        assert(meta != NULL);
./numpy/core/src/multiarray/datetime.c:3956:            assert(meta != NULL);
./numpy/core/src/multiarray/datetime.c:4003:        assert(descrs[1]->type_num == NPY_UNICODE);
./numpy/core/src/multiarray/datetime.c:4062:        assert(descrs[0]->type_num == NPY_UNICODE);
./numpy/core/src/multiarray/textreading/rows.c:36:    assert(converters != Py_None);
./numpy/core/src/multiarray/textreading/rows.c:191:        assert(homogeneous || num_field_types == num_usecols);
./numpy/core/src/multiarray/textreading/rows.c:195:        assert(usecols == NULL || num_field_types == num_usecols);
./numpy/core/src/multiarray/textreading/rows.c:314:                assert(max_rows >=0);
./numpy/core/src/multiarray/textreading/rows.c:438:        assert(row_count == 0 && result_shape[0] == 0);
./numpy/core/src/multiarray/textreading/field_types.c:15:    assert(num_field_types >= 0);
./numpy/core/src/multiarray/textreading/field_types.c:51:                assert(0);
./numpy/core/src/multiarray/textreading/field_types.c:65:                assert(0);
./numpy/core/src/multiarray/textreading/growth.c:21:    assert((min_grow & (min_grow - 1)) == 0);
./numpy/core/src/npymath/halffloat.c:433:        assert(d_exp - 998 >= 0);
./numpy/core/src/common/numpyos.c:87:            assert(extra_zeros_cnt >= 0);
./numpy/core/src/common/mem_overlap.c:213:    assert(a1 > 0);
./numpy/core/src/common/mem_overlap.c:214:    assert(a2 > 0);
./numpy/core/src/common/mem_overlap.c:266:    assert(n >= 2);
./numpy/core/src/common/npy_hashtable.c:98:    assert(key_len > 0);
./numpy/core/src/common/npy_hashtable.c:126:    assert(prev_size > 0);
./numpy/core/src/common/npy_hashtable.c:142:        assert(new_size >= 4);
./numpy/core/src/common/npy_argparse.c:361:    assert(len_args + len_kwargs <= cache->nargs);
./numpy/core/src/common/npy_argparse.c:397:        assert(0);
./numpy/core/src/umath/legacy_array_method.c:200:    assert(aligned);
./numpy/core/src/umath/legacy_array_method.c:201:    assert(!move_references);
./numpy/core/src/umath/ufunc_object.c:1220:    assert(context->method->nout == 1);
./numpy/core/src/umath/ufunc_object.c:1238:            assert(iop == nin);
./numpy/core/src/umath/ufunc_object.c:1422:        assert(PyArray_TYPE(op[nop]) == NPY_BOOL);
./numpy/core/src/umath/ufunc_object.c:1972:            assert(core_start_dim >= 0);
./numpy/core/src/umath/ufunc_object.c:2226:        assert(!(axes != NULL && axis != NULL));
./numpy/core/src/umath/ufunc_object.c:2495:    assert(!NpyIter_IsBuffered(iter));
./numpy/core/src/umath/ufunc_object.c:2836:        assert(!masked);  /* Path currently not available for masked */
./numpy/core/src/umath/ufunc_object.c:3057:    assert(PyArray_EquivTypes(descrs[0], descrs[1])
./numpy/core/src/umath/ufunc_object.c:3474:    assert(PyArray_EquivTypes(descrs[0], descrs[1])
./numpy/core/src/umath/ufunc_object.c:3583:        assert(out == NULL);
./numpy/core/src/umath/ufunc_object.c:4385:    assert(signature_obj != NULL);
./numpy/core/src/umath/wrapping_array_method.c:149:    assert(move_references == 0);  /* only used internally for "decref" funcs */
./numpy/core/src/umath/reduction.c:189:    assert(loop != NULL);
./numpy/core/src/umath/reduction.c:245:        assert(op_dtypes[2]->type_num == NPY_BOOL);
./numpy/core/src/umath/override.c:183:            assert(strcmp(keywords[i], "initial") == 0);
./numpy/core/src/umath/dispatching.c:229:            assert((PyObject *)given_dtype != Py_None);
./numpy/core/src/umath/dispatching.c:854:            assert(i >= ufunc->nin || !NPY_DT_is_abstract(signature[i]));
./numpy/core/src/umath/dispatching.c:918:            assert((PyObject *)signature[i] == PyTuple_GET_ITEM(all_dtypes, i));
./numpy/core/src/umath/dispatching.c:946:    assert(ufunc->nin > 1);
./numpy/core/src/umath/dispatching.c:948:        assert(ufunc->nin == 2 && ufunc->nout == 1);  /* must be reduction */
./numpy/core/src/umath/ufunc_type_resolution.c:1812:    assert(n_specified == nop);
./numpy/linalg/linalg.py:2803:        assert out is None
./numpy/ma/timer_comparison.py:80:                assert cond, msg
./numpy/ma/timer_comparison.py:98:                assert cond, msg
./numpy/ma/timer_comparison.py:137:        assert((xm-ym).filled(0).any())
./numpy/ma/timer_comparison.py:139:        assert(xm.size == reduce(lambda x, y:x*y, s))
./numpy/ma/timer_comparison.py:140:        assert(self.count(xm) == len(m1) - reduce(lambda x, y:x+y, m1))
./numpy/ma/timer_comparison.py:148:            assert(self.count(xm) == len(m1) - reduce(lambda x, y:x+y, m1))
./numpy/ma/timer_comparison.py:164:        assert type(x2[1]) is type(x1[1])
./numpy/ma/timer_comparison.py:165:        assert x1[1] == x2[1]
./numpy/ma/timer_comparison.py:184:        assert x1[1:1].shape == (0,)
./numpy/ma/timer_comparison.py:189:        assert(m is m2)
./numpy/ma/timer_comparison.py:191:        assert(m is not m3)
./numpy/ma/timer_comparison.py:202:        assert self.allequal(self.concatenate([x4, x4]), y4)
./numpy/ma/timer_comparison.py:203:        assert self.allequal(self.getmask(y4), [0, 0, 1, 0, 0, 0, 1, 0])
./numpy/ma/timer_comparison.py:207:        assert self.allequal(y5, y6)
./numpy/ma/timer_comparison.py:209:        assert self.allequal(y5, y7)
./numpy/ma/timer_comparison.py:211:        assert self.allequal(y5, y8)
./numpy/ma/timer_comparison.py:224:        assert self.allequal(np.transpose(y, (2, 0, 1)), self.transpose(x, (2, 0, 1)))
./numpy/ma/timer_comparison.py:225:        assert self.allequal(np.take(y, (2, 0, 1), 1), self.take(x, (2, 0, 1), 1))
./numpy/ma/timer_comparison.py:226:        assert self.allequal(np.inner(self.filled(x, 0), self.filled(y, 0)),
./numpy/ma/timer_comparison.py:228:        assert self.allequal(np.outer(self.filled(x, 0), self.filled(y, 0)),
./numpy/ma/timer_comparison.py:233:        assert t[0] == 'abc'
./numpy/ma/timer_comparison.py:234:        assert t[1] == 2
./numpy/ma/timer_comparison.py:235:        assert t[2] == 3
./numpy/ma/timer_comparison.py:248:        assert self.allequal(x, y+1)
./numpy/ma/timer_comparison.py:250:        assert self.allequal(xm, y+1)
./numpy/ma/timer_comparison.py:256:        assert self.allequal(x, y-1)
./numpy/ma/timer_comparison.py:258:        assert self.allequal(xm, y-1)
./numpy/ma/timer_comparison.py:264:        assert self.allequal(x, y*2)
./numpy/ma/timer_comparison.py:266:        assert self.allequal(xm, y*2)
./numpy/ma/timer_comparison.py:272:        assert self.allequal(x, y)
./numpy/ma/timer_comparison.py:274:        assert self.allequal(xm, y)
./numpy/ma/timer_comparison.py:280:        assert self.allequal(x, y/2.0)
./numpy/ma/timer_comparison.py:288:        assert self.allequal(x, y + 1.)
./numpy/ma/timer_comparison.py:305:        assert self.allequal(x, y+a)
./numpy/ma/timer_comparison.py:306:        assert self.allequal(xm, y+a)
./numpy/ma/timer_comparison.py:307:        assert self.allequal(xm.mask, self.mask_or(m, a.mask))
./numpy/ma/timer_comparison.py:317:        assert self.allequal(x, y-a)
./numpy/ma/timer_comparison.py:318:        assert self.allequal(xm, y-a)
./numpy/ma/timer_comparison.py:319:        assert self.allequal(xm.mask, self.mask_or(m, a.mask))
./numpy/ma/timer_comparison.py:329:        assert self.allequal(x, y*a)
./numpy/ma/timer_comparison.py:330:        assert self.allequal(xm, y*a)
./numpy/ma/timer_comparison.py:331:        assert self.allequal(xm.mask, self.mask_or(m, a.mask))
./numpy/ma/timer_comparison.py:385:        assert(wts == 4.0)
./numpy/ma/timer_comparison.py:387:        assert(self.average(ott, axis=0) is self.masked)
./numpy/ma/timer_comparison.py:392:        assert(self.average(ott, axis=1)[0] is self.masked)
./numpy/_version.py:72:    assert isinstance(commands, list)
./numpy/f2py/cfuncs.py:668:        assert(ISCONTIGUOUS(arr));
./numpy/f2py/crackfortran.py:636:    assert not (set('"\'') & set(characters)), "cannot split by unquoted quotes"
./numpy/f2py/crackfortran.py:677:        assert reset == 0, repr(reset)
./numpy/f2py/crackfortran.py:854:    assert not f, repr((f, line, l))
./numpy/f2py/crackfortran.py:1143:            assert result is None, repr(result)
./numpy/f2py/f2py2e.py:576:    assert len(flib_flags) <= 2, repr(flib_flags)
./numpy/f2py/func2subr.py:79:    assert isfunction(rout)
./numpy/f2py/func2subr.py:185:    assert issubroutine(rout)
./numpy/f2py/symbolic.py:163:        assert isinstance(op, Op)
./numpy/f2py/symbolic.py:169:            assert isinstance(data, tuple) and len(data) == 2
./numpy/f2py/symbolic.py:170:            assert isinstance(data[0], int)
./numpy/f2py/symbolic.py:171:            assert isinstance(data[1], (int, str)), data
./numpy/f2py/symbolic.py:175:            assert isinstance(data, tuple) and len(data) == 2
./numpy/f2py/symbolic.py:176:            assert isinstance(data[0], float)
./numpy/f2py/symbolic.py:177:            assert isinstance(data[1], (int, str)), data
./numpy/f2py/symbolic.py:180:            assert isinstance(data, tuple) and len(data) == 2
./numpy/f2py/symbolic.py:184:            assert isinstance(data, tuple) and len(data) == 2
./numpy/f2py/symbolic.py:185:            assert (isinstance(data[0], str)
./numpy/f2py/symbolic.py:187:            assert isinstance(data[1], (int, str)), data
./numpy/f2py/symbolic.py:190:            assert hash(data) is not None
./numpy/f2py/symbolic.py:193:            assert isinstance(data, tuple)
./numpy/f2py/symbolic.py:194:            assert all(isinstance(item, Expr) for item in data), data
./numpy/f2py/symbolic.py:198:            assert isinstance(data, dict)
./numpy/f2py/symbolic.py:202:            assert isinstance(data, tuple) and len(data) == 3
./numpy/f2py/symbolic.py:204:            assert hash(data[0]) is not None
./numpy/f2py/symbolic.py:205:            assert isinstance(data[1], tuple)
./numpy/f2py/symbolic.py:206:            assert isinstance(data[2], dict)
./numpy/f2py/symbolic.py:209:            assert isinstance(data, tuple) and len(data) == 2
./numpy/f2py/symbolic.py:211:            assert hash(data[0]) is not None
./numpy/f2py/symbolic.py:214:            assert isinstance(data, tuple) and len(data) == 3
./numpy/f2py/symbolic.py:217:            assert isinstance(data, Expr)
./numpy/f2py/symbolic.py:220:            assert isinstance(data, tuple) and len(data) == 3
./numpy/f2py/symbolic.py:593:                assert paren == 'ROUND', (paren, value)
./numpy/f2py/symbolic.py:840:            assert isinstance(coeff, number_types)
./numpy/f2py/symbolic.py:1188:    assert '"' not in new_s
./numpy/f2py/symbolic.py:1189:    assert "'" not in new_s
./numpy/f2py/symbolic.py:1249:    assert s.startswith('@__f2py_PARENTHESIS_'), s
./numpy/f2py/symbolic.py:1323:        assert isinstance(s, str), (type(s), s)
./numpy/f2py/symbolic.py:1350:            assert context == 'expr', context
./numpy/f2py/symbolic.py:1389:                    assert op == '-'
./numpy/f2py/symbolic.py:1416:                    assert op == '/'
./numpy/f2py/symbolic.py:1498:                assert paren == 'SQUARE'
./numpy/lib/format.py:371:    assert version is not None
./numpy/random/_examples/cffi/extending.py:40:    assert vals[i] == vals_cffi[i]
./doc/source/conf.py:43:    assert 'numpy.core._add_newdocs_scalars' not in sys.modules
./doc/source/reference/simd/gen_features.py:117:        assert(not rows or len(field_names) == len(rows[0]))
./venv/lib/python3.9/site-packages/lizard.py:82:                        assert. -ENS: count nested control structures.''',
./venv/lib/python3.9/site-packages/wheel/macosx_libfile.py:370:    assert len(base_version) == 2
./venv/lib/python3.9/site-packages/wheel/macosx_libfile.py:387:    assert len(base_version) == 2
./venv/lib/python3.9/site-packages/wheel/bdist_wheel.py:287:            assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
./venv/lib/python3.9/site-packages/wheel/bdist_wheel.py:428:                    logger.debug('ignoring license file "%s" as it looks like a backup', path)
./venv/lib/python3.9/site-packages/wheel/vendored/packaging/tags.py:177:        logger.debug(
./venv/lib/python3.9/site-packages/wheel/vendored/packaging/tags.py:541:        assert version_string is not None
./venv/lib/python3.9/site-packages/pytz/tzfile.py:31:    assert magic == _byte_string('TZif'), 'Got magic %s' % repr(magic)
./venv/lib/python3.9/site-packages/pytz/tzfile.py:40:    assert len(data) == 2 * timecnt + 3 * typecnt + 1
./venv/lib/python3.9/site-packages/pytz/tzinfo.py:392:            assert utc_time not in dates
./venv/lib/python3.9/site-packages/pytz/reference.py:124:        assert dt.tzinfo is self
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:130:        assert self.load_only is not None, "Need to be specified a file to be editing"
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:154:        assert self.load_only
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:172:        assert self.load_only
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:215:        logger.debug("Will be working with %s variant only", self.load_only)
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:233:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:244:                    logger.debug("Skipping file '%s' (variant: %s)", fname, variant)
./venv/lib/python3.9/site-packages/pip/_internal/configuration.py:348:        assert self.load_only
./venv/lib/python3.9/site-packages/pip/_internal/pyproject.py:97:    assert use_pep517 is not None
./venv/lib/python3.9/site-packages/pip/_internal/pyproject.py:122:    assert build_system is not None
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:52:            logger.debug("Getting credentials from keyring for %s", url)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:59:            logger.debug("Getting password from keyring for %s", url)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:124:            logger.debug("Found credentials in url for %s", netloc)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:134:                logger.debug("Found index url %s", index_url)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:140:                logger.debug("Found credentials in index url for %s", netloc)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:147:                logger.debug("Found credentials in netrc for %s", netloc)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:160:                logger.debug("Found credentials in keyring for %s", netloc)
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:204:        assert (
./venv/lib/python3.9/site-packages/pip/_internal/network/auth.py:312:        assert keyring is not None, "should never reach here without keyring"
./venv/lib/python3.9/site-packages/pip/_internal/network/xmlrpc.py:39:        assert isinstance(host, str)
./venv/lib/python3.9/site-packages/pip/_internal/network/xmlrpc.py:54:            assert exc.response
./venv/lib/python3.9/site-packages/pip/_internal/network/download.py:135:            assert e.response is not None
./venv/lib/python3.9/site-packages/pip/_internal/network/download.py:169:                assert e.response is not None
./venv/lib/python3.9/site-packages/pip/_internal/network/cache.py:38:        assert directory is not None, "Cache directory must not be None."
./venv/lib/python3.9/site-packages/pip/_internal/network/lazy_wheel.py:54:        assert head.status_code == 200
./venv/lib/python3.9/site-packages/pip/_internal/cache.py:44:        assert not cache_dir or os.path.isabs(cache_dir)
./venv/lib/python3.9/site-packages/pip/_internal/cache.py:50:        assert self.allowed_formats.union(_valid_formats) == _valid_formats
./venv/lib/python3.9/site-packages/pip/_internal/cache.py:139:        assert self.cache_dir
./venv/lib/python3.9/site-packages/pip/_internal/cache.py:161:                logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/utils/logging.py:157:            assert isinstance(diagnostic_error, DiagnosticPipError)
./venv/lib/python3.9/site-packages/pip/_internal/utils/encoding.py:31:            assert result is not None
./venv/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py:161:        assert proc.stdout
./venv/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py:162:        assert proc.stdin
./venv/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py:176:                assert spinner
./venv/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py:199:        assert spinner
./venv/lib/python3.9/site-packages/pip/_internal/utils/filesystem.py:24:    assert os.path.isabs(path)
./venv/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py:23:        assert isinstance(direct_url.info, DirInfo)
./venv/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py:44:        assert vcs_backend
./venv/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py:55:            assert requested_revision
./venv/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py:61:            assert source_dir
./venv/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py:133:            assert _tempdir_manager is not None
./venv/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py:138:        assert not self._deleted, f"Attempted to access deleted path: {self._path}"
./venv/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py:165:        logger.debug("Created temporary directory: %s", path)
./venv/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py:245:        logger.debug("Created temporary directory: %s", path)
./venv/lib/python3.9/site-packages/pip/_internal/utils/setuptools_build.py:113:    assert not (use_user_site and prefix)
./venv/lib/python3.9/site-packages/pip/_internal/utils/setuptools_build.py:164:    assert not (use_user_site and prefix)
./venv/lib/python3.9/site-packages/pip/_internal/utils/setuptools_build.py:165:    assert not (use_user_site and root)
./venv/lib/python3.9/site-packages/pip/_internal/utils/urls.py:30:    assert url.startswith(
./venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py:32:    logger.debug("bz2 module is not available")
./venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py:40:    logger.debug("lzma module is not available")
./venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py:217:                assert fp is not None
./venv/lib/python3.9/site-packages/pip/_internal/models/link.py:116:        assert name, f"URL {self._url!r} produced no filename"
./venv/lib/python3.9/site-packages/pip/_internal/models/link.py:222:        assert self.hash_name is not None
./venv/lib/python3.9/site-packages/pip/_internal/models/link.py:223:        assert self.hash is not None
./venv/lib/python3.9/site-packages/pip/_internal/models/link.py:268:        logger.debug("Ignoring egg= fragment in %s", link)
./venv/lib/python3.9/site-packages/pip/_internal/models/direct_url.py:60:    assert infos[0] is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:51:            assert option.dest is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:112:            assert isinstance(self.parser, ConfigOptionParser)
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:114:            assert option.dest is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:168:        assert self.name
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:189:                logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:223:            assert option.dest is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:250:                assert option.callback is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py:283:            assert option.dest is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/command_context.py:15:        assert not self._in_main_context
./venv/lib/python3.9/site-packages/pip/_internal/cli/command_context.py:25:        assert self._in_main_context
./venv/lib/python3.9/site-packages/pip/_internal/cli/spinners.py:46:        assert not self._finished
./venv/lib/python3.9/site-packages/pip/_internal/cli/spinners.py:85:        assert not self._finished
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:89:        assert not hasattr(options, "no_index")
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:168:                    assert isinstance(status, int)
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:172:                    logger.debug("Exception information:", exc_info=True)
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:177:                    logger.debug("Exception information:", exc_info=True)
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:187:                    logger.debug("Exception information:", exc_info=True)
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:192:                    logger.debug("Exception information:", exc_info=True)
./venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py:205:                    logger.debug("Exception information:", exc_info=True)
./venv/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py:279:    assert bar_type == "on", "This should only be used in the default mode."
./venv/lib/python3.9/site-packages/pip/_internal/cli/main.py:67:        logger.debug("Ignoring error %s when setting locale", e)
./venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py:79:            assert self._session is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py:88:        assert not options.cache_dir or os.path.isabs(options.cache_dir)
./venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py:138:        assert hasattr(options, "no_index")
./venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py:200:        assert self.tempdir_registry is not None
./venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py:271:        assert temp_build_dir_path is not None
./venv/lib/python3.9/site-packages/pip/_internal/operations/install/legacy.py:103:                logger.debug("Record file %s not found", record_filename)
./venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py:98:    assert os.path.isfile(path)
./venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py:498:            assert_no_path_traversal(dest, dest_path)
./venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py:531:            assert_no_path_traversal(scheme_path, dest_path)
./venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py:618:                        assert os.path.exists(pyc_path)
./venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py:623:        logger.debug(stdout.getvalue())
./venv/lib/python3.9/site-packages/pip/_internal/operations/freeze.py:159:    assert editable_project_location
./venv/lib/python3.9/site-packages/pip/_internal/operations/freeze.py:168:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel_legacy.py:80:        logger.debug("Destination directory: %s", tempd)
./venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel_editable.py:22:    assert metadata_directory is not None
./venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel_editable.py:24:        logger.debug("Destination directory: %s", tempd)
./venv/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py:47:    logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel.py:22:    assert metadata_directory is not None
./venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel.py:24:        logger.debug("Destination directory: %s", tempd)
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:64:    assert vcs_backend is not None
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:338:        assert req.source_dir is None
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:406:            logger.debug("Lazy wheel is not used as hash checking is required")
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:409:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:426:            logger.debug("%s does not support range requests", url)
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:444:            assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:452:            logger.debug("Downloading link %s to %s", link, filepath)
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:465:        assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:522:        assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:565:        assert self.download_dir is not None
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:566:        assert req.link is not None
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:574:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:595:        assert req.editable, "cannot prepare a non-editable req as editable"
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:626:        assert req.satisfied_by, "req should have been satisfied but isn't"
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:627:        assert skip_reason is not None, (
./venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py:636:                logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:88:        assert req is None or isinstance(req, Requirement), req
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:103:            assert link
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:223:        assert self.pep517_backend
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:304:        assert build_dir is not None
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:306:            assert self._temp_build_dir.path
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:331:            logger.debug("Creating directory %s", build_dir)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:346:        assert self.req is None
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:347:        assert self.metadata is not None
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:348:        assert self.source_dir is not None
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:436:        assert self.source_dir, f"No source dir for {self}"
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:443:        assert self.source_dir, f"No source dir for {self}"
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:450:        assert self.source_dir, f"No source dir for {self}"
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:506:        assert self.source_dir
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:510:            assert self.pep517_backend is not None
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:555:        assert self.source_dir
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:564:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:597:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:602:        assert self.editable
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:603:        assert self.source_dir
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:610:        assert vcs_backend, f"Unsupported VCS URL {self.link.url}"
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:630:        assert self.req
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:643:            assert name.startswith(
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:659:        assert self.source_dir
./venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py:759:            assert self.local_file_path
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:37:                assert isinstance(original_value, str)  # for mypy
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:48:            logger.debug("Initialized build tracking at %s", root)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:58:        logger.debug("Created build tracker: %s", self._root)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:61:        logger.debug("Entered build tracker: %s", self._root)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:79:        assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:95:        assert req not in self._entries
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:102:        logger.debug("Added %s to build tracker %r", req, self._root)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:107:        assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:112:        logger.debug("Removed %s from build tracker %r", req, self._root)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py:118:        logger.debug("Removed build tracker: %r", self._root)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_set.py:45:        assert not install_req.name
./venv/lib/python3.9/site-packages/pip/_internal/req/req_set.py:49:        assert install_req.name
./venv/lib/python3.9/site-packages/pip/_internal/req/req_set.py:98:        assert (
./venv/lib/python3.9/site-packages/pip/_internal/req/req_set.py:162:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py:65:    assert location is not None, "not installed"
./venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py:284:                logger.debug("Replacing %s from %s", new_path, path)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py:292:                logger.debug("Exception: %s", ex)
./venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py:530:            assert link_pointer == dist_location, (
./venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py:541:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py:630:        logger.debug("Rolling %s back to previous state", self.file)
./venv/lib/python3.9/site-packages/pip/_internal/req/__init__.py:33:        assert req.name, f"invalid to-be-installed requirement: {req}"
./venv/lib/python3.9/site-packages/pip/_internal/req/req_file.py:177:    assert line.is_requirement
./venv/lib/python3.9/site-packages/pip/_internal/req/req_file.py:458:                assert primary_line_number is not None
./venv/lib/python3.9/site-packages/pip/_internal/req/req_file.py:470:        assert primary_line_number is not None
./venv/lib/python3.9/site-packages/pip/_internal/req/constructors.py:156:        logger.debug("Cannot parse '%s' as requirements file", req)
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:94:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:131:        assert upgrade_strategy in self._allowed_strategies
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:197:            assert self.upgrade_strategy == "only-if-needed"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:310:            logger.debug("Using cached wheel link: %s", cache_entry.link)
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:324:        assert req.satisfied_by is None
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:412:                assert req_to_install.user_supplied
./venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py:417:                    logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py:259:        assert template.req, "Candidates found on index must be PEP 508"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py:264:            assert ireq.req, "Candidates found on index must be PEP 508"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py:359:            assert base_cand is not None, "no extras here"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py:499:                assert ireq.name, "Constraint must be named"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py:592:        assert causes, "Requires-Python error reported with no cause"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py:644:        assert e.causes, "Installation error reported with no cause"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py:44:        assert ireq.link is None, "This is a link, not a specifier"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py:59:        assert self._ireq.req, "Specifier-backed ireq is always PEP 508"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py:84:        assert candidate.name == self.name, (
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py:91:        assert self._ireq.req, "Specifier-backed ireq is always PEP 508"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py:129:        assert candidate.name == self._candidate.name, "Not Python candidate"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py:54:        assert upgrade_strategy in self._allowed_strategies
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py:181:        assert self._result is not None, "must call resolve() first"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py:282:    assert not difference, difference
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py:55:    assert not template.editable, "template is editable"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py:81:    assert template.editable, "template not editable"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py:266:            logger.debug("Using cached wheel link: %s", cache_entry.link)
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py:269:        assert ireq.link == link
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py:273:            assert name == wheel_name, f"{name!r} != {wheel_name!r} for wheel"
./venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py:277:                assert version == wheel_version, "{!r} != {!r} for wheel {}".format(
./venv/lib/python3.9/site-packages/pip/_internal/vcs/git.py:214:        assert rev is not None
./venv/lib/python3.9/site-packages/pip/_internal/vcs/git.py:292:            logger.debug("Rev options %s, branch_name %s", rev_options, branch_name)
./venv/lib/python3.9/site-packages/pip/_internal/vcs/git.py:477:            assert "file:" not in url
./venv/lib/python3.9/site-packages/pip/_internal/vcs/git.py:510:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/vcs/mercurial.py:152:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py:225:            logger.debug("Registered VCS backend: %s", cls.name)
./venv/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py:241:            logger.debug("Determine that %s uses VCS: %s", location, vcs_backend.name)
./venv/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py:528:                logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py:688:        logger.debug("Checking in %s for %s (%s)...", path, cls.dirname, cls.name)
./venv/lib/python3.9/site-packages/pip/_internal/vcs/subversion.py:65:                assert dirurl is not None
./venv/lib/python3.9/site-packages/pip/_internal/vcs/subversion.py:169:                assert match is not None
./venv/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py:56:    assert obj is not None
./venv/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py:61:    assert not (user and prefix), f"user={user} prefix={prefix}"
./venv/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py:62:    assert not (home and prefix), f"home={home} prefix={prefix}"
./venv/lib/python3.9/site-packages/pip/_internal/index/collector.py:121:    logger.debug("Getting page %s", redact_auth_from_url(url))
./venv/lib/python3.9/site-packages/pip/_internal/index/collector.py:275:        assert page.cache_link_parsing
./venv/lib/python3.9/site-packages/pip/_internal/index/collector.py:468:        logger.debug(" file: URL is directory, getting %s", url)
./venv/lib/python3.9/site-packages/pip/_internal/index/collector.py:539:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/collector.py:605:            logger.debug("\n".join(lines))
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:70:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:87:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:229:        logger.debug("Found link %s, version: %s", link, version)
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:255:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:294:    logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:346:        assert set(applicable_candidates) <= set(candidates)
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:349:            assert not applicable_candidates
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:351:            assert best_candidate in applicable_candidates
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:726:            logger.debug("Skipping link: %s: %s", reason, link)
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:765:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:825:                assert candidate.link.url  # we need to have a URL
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:831:            logger.debug("Local files found: %s", ", ".join(paths))
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:932:                logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:938:                logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:948:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py:955:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/exceptions.py:80:            assert hasattr(self, "reference"), "error reference not provided!"
./venv/lib/python3.9/site-packages/pip/_internal/exceptions.py:82:        assert _is_kebab_case(reference), "error reference must be kebab-case!"
./venv/lib/python3.9/site-packages/pip/_internal/exceptions.py:656:            assert self.error is not None
./venv/lib/python3.9/site-packages/pip/_internal/commands/download.py:134:                assert req.name is not None
./venv/lib/python3.9/site-packages/pip/_internal/commands/search.py:84:        assert isinstance(hits, list)
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:463:            assert target_temp_dir
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:552:            assert resolver_variant == "2020-resolver"
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:635:        logger.debug("Non-user install by explicit request")
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:649:        logger.debug("User install by explicit request")
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:653:    assert use_user_site is None
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:657:        logger.debug("Non-user install due to --prefix or --target option")
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:662:        logger.debug("Non-user install because user site-packages disabled")
./venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:668:        logger.debug("Non-user install because site-packages writeable")
./venv/lib/python3.9/site-packages/pip/_internal/commands/wheel.py:163:            assert req.link and req.link.is_wheel
./venv/lib/python3.9/site-packages/pip/_internal/commands/wheel.py:164:            assert req.local_file_path
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:129:        assert not req.editable
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:130:        assert req.source_dir
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:132:        assert vcs_backend
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:137:    assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:154:    assert req.link
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:242:        assert req.name
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:244:            assert req.metadata_directory
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:245:            assert req.pep517_backend
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:346:            assert req.name
./venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py:360:                assert req.link.is_wheel
./venv/lib/python3.9/site-packages/pip/_internal/metadata/pkg_resources.py:88:            assert dist_dir.endswith(".dist-info")
./venv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py:53:        assert pyproject_requires is not None
./venv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py:79:            assert backend is not None
./venv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py:89:            assert backend is not None
./venv/lib/python3.9/site-packages/pip/_internal/distributions/installed.py:14:        assert self.req.satisfied_by is not None, "not actually installed"
./venv/lib/python3.9/site-packages/pip/_internal/distributions/wheel.py:23:        assert self.req.local_file_path, "Set as part of preparation during download"
./venv/lib/python3.9/site-packages/pip/_internal/distributions/wheel.py:24:        assert self.req.name, "Wheels are never unnamed"
./venv/lib/python3.9/site-packages/pip/_internal/self_outdated_check.py:186:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_internal/build_env.py:122:                    assert not path in sys.path
./venv/lib/python3.9/site-packages/pip/_internal/build_env.py:196:        assert not prefix.setup
./venv/lib/python3.9/site-packages/pip/_vendor/packaging/tags.py:115:        logger.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/packaging/_musllinux.py:130:    assert plat.startswith("linux-"), "not linux"
./venv/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py:152:    assert isinstance(marker, (list, tuple, str))
./venv/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py:226:        assert isinstance(marker, (list, tuple, str))
./venv/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py:242:            assert marker in ["and", "or"]
./venv/lib/python3.9/site-packages/pip/_vendor/packaging/_manylinux.py:146:        assert version_string is not None
./venv/lib/python3.9/site-packages/pip/_vendor/msgpack/fallback.py:373:        assert self._feeding
./venv/lib/python3.9/site-packages/pip/_vendor/msgpack/fallback.py:435:            assert isinstance(read_data, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/msgpack/fallback.py:619:        assert typ == TYPE_IMMEDIATE
./venv/lib/python3.9/site-packages/pip/_vendor/msgpack/fallback.py:835:                assert isinstance(code, int)
./venv/lib/python3.9/site-packages/pip/_vendor/msgpack/fallback.py:836:                assert isinstance(data, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/sjisprober.py:60:                self.logger.debug('%s %s prober hit error at byte %s',
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/mbcharsetprober.py:65:                self.logger.debug('%s %s prober hit error at byte %s',
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/universaldetector.py:234:            self.logger.debug('no data received!')
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/universaldetector.py:271:                self.logger.debug('no probers hit minimum threshold')
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/universaldetector.py:277:                            self.logger.debug('%s %s confidence = %s',
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/universaldetector.py:282:                        self.logger.debug('%s %s confidence = %s',
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/eucjpprober.py:61:                self.logger.debug('%s %s prober hit error at byte %s',
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/sbcharsetprober.py:125:                    self.logger.debug('%s confidence = %s, we have a winner',
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/sbcharsetprober.py:129:                    self.logger.debug('%s confidence = %s, below negative '
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/charsetgroupprober.py:98:                self.logger.debug('%s not active', prober.charset_name)
./venv/lib/python3.9/site-packages/pip/_vendor/chardet/charsetgroupprober.py:101:            self.logger.debug('%s %s confidence = %s', prober.charset_name, prober.language, conf)
./venv/lib/python3.9/site-packages/pip/_vendor/webencodings/mklabels.py:21:    assert string == string.lower()
./venv/lib/python3.9/site-packages/pip/_vendor/webencodings/__init__.py:224:            assert decoder.encoding is not None
./venv/lib/python3.9/site-packages/pip/_vendor/webencodings/__init__.py:231:        assert decoder.encoding is not None
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/style.py:79:            assert False, "wrong color format %r" % text
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/formatters/other.py:126:        assert list(lexer.get_tokens(fragment)) == tokens
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:428:        assert type(token) is _TokenType or callable(token), \
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:445:                assert False, 'unknown new state %r' % new_state
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:452:                assert istate != new_state, 'circular state ref %r' % istate
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:460:                assert (istate in unprocessed or
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:465:            assert False, 'unknown new state def %r' % new_state
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:469:        assert type(state) is str, "wrong state name %r" % state
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:470:        assert state[0] != '#', "invalid state name %r" % state
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:478:                assert tdef != state, "circular state reference %r" % state
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:492:            assert type(tdef) is tuple, "wrong rule def %r" % tdef
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:659:                            assert False, "wrong state def: %r" % new_state
./venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py:747:                            assert False, "wrong state def: %r" % new_state
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/_backport/shutil.py:568:            logger.debug("changing into '%s'", root_dir)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/_backport/shutil.py:596:                logger.debug("changing back to '%s'", save_cwd)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/_backport/sysconfig.py:75:        assert _cfgfile, 'sysconfig.cfg exists'
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:220:                logger.debug('Not replacing %r with %r', url1, url2)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:222:                logger.debug('Replacing %r with %r', url1, url2)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:245:            logger.debug('%s: version hint in fragment: %r',
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:259:                    logger.debug('Wheel not compatible: %s', path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:278:            logger.debug('Not downloadable: %s', path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:286:                        logger.debug('No match for project/version: %s', path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:370:        logger.debug('matcher: %s (%s)', matcher, type(matcher).__name__)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:381:                        pass  # logger.debug('%s did not match %r', matcher, k)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:386:                            # logger.debug('skipping pre-release '
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:394:                logger.debug('sorted list: %s', slist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:663:                logger.debug('Queueing %s', url)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:694:        logger.debug('process_download: %s -> %s', url, info)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:725:        logger.debug('should_queue: %s (%s) from %s -> %s', link, rel,
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:749:                                    logger.debug('Queueing %s from %s', link, url)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:759:                #logger.debug('Sentinel seen, quitting.')
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:777:            logger.debug('Returning %s from cache: %s', url, result)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:782:                logger.debug('Skipping %s due to bad host %s', url, host)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:786:                    logger.debug('Fetching %s', url)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:788:                    logger.debug('Fetched %s', url)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:950:        assert isinstance(distpath, DistributionPath)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1085:        logger.debug('adding distribution %s', dist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1091:            logger.debug('Add to provided: %s, %s, %s', name, version, dist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1100:        logger.debug('removing distribution %s', dist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1106:            logger.debug('Remove from provided: %s, %s, %s', name, version, dist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1231:            logger.debug('passed %s as requirement', odist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1237:            logger.debug('located %s', odist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1265:                    logger.debug('No providers found for %r', r)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1272:                        logger.debug('Cannot satisfy %r', r)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1281:                            logger.debug('Adding %s to install_dists',
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1297:                logger.debug('%s is a build-time dependency only.',
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/locators.py:1299:        logger.debug('find done for %s', odist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:148:            logger.debug('Removed 1.0 due to %s', key)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:151:            logger.debug('Removed 1.1 due to %s', key)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:154:            logger.debug('Removed 1.2 due to %s', key)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:157:            logger.debug('Removed 1.3 due to %s', key)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:161:                logger.debug('Removed 2.1 due to %s', key)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:164:            logger.debug('Removed 2.0 due to %s', key)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:170:        logger.debug('Out of options - unknown metadata set: %s', fields)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:365:        # logger.debug('Attempting to set metadata for %s', self)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:920:        assert self._legacy and not self._data
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/metadata.py:983:        assert self._data and not self._legacy
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/version.py:34:        assert isinstance(parts, tuple)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/version.py:35:        assert len(parts) > 0
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/compat.py:625:            assert path.endswith('.py')
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/index.py:142:            logger.debug('%s: %s' % (name, s))
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/index.py:171:        logger.debug('invoking: %s', ' '.join(cmd))
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/index.py:338:        logger.debug('invoking: %s', ' '.join(cmd))
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/index.py:390:            logger.debug('No digest specified')
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/index.py:397:            logger.debug('Digest specified: %s' % digest)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/index.py:441:            logger.debug('Digest verified: %s', digest)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/manifest.py:110:            logger.debug('add_dir added %s', d)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/manifest.py:113:                assert parent not in ('', '/')
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/manifest.py:339:                assert pattern_re.startswith(start) and pattern_re.endswith(end)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/manifest.py:351:                assert prefix_re.startswith(start) and prefix_re.endswith(end)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:277:        assert path.startswith(root)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:363:                assert entry is not None
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:390:            assert entry is not None
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:537:        assert not os.path.isdir(outfile)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:597:                    assert path.startswith(prefix)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:609:                logger.debug('Removing directory tree at %s', path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:620:                logger.debug('Removing %s %s', s, path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:644:        assert self.record
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:661:                    assert flist == ['__pycache__']
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:837:    assert i is not None
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:923:            logger.debug('Unexpected response for JSON request: %s', ct)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1056:        logger.debug('publish %s: args = %s, kwargs = %s, result = %s',
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1089:        assert pred != succ
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1094:        assert pred != succ
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1283:        assert maxval is None or maxval >= minval
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1291:        assert self.min <= curval
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1292:        assert self.max is None or curval <= self.max
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1301:        assert incr >= 0
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1391:        assert len(rich_path_glob) == 3, rich_path_glob
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py:1461:                    logger.debug('Host verified: %s', self.host)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:149:                    logger.debug('Found %s', r.path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:155:                    logger.debug('Found %s', r.path)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:274:                logger.debug('No "provides": %s', dist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:382:        logger.debug('Getting requirements from metadata %r', md.todict())
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:1135:        logger.debug('%s missing %r', distribution, requirement)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:1212:            logger.debug('Moving to result: %s',
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/database.py:1243:            logger.debug('Add to provided: %s, %s, %s', name, version, dist)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/markers.py:72:            assert isinstance(expr, dict)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/resources.py:239:            logger.debug('_find failed: %r %r', path, self.loader.prefix)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/resources.py:241:            logger.debug('_find worked: %r %r', path, self.loader.prefix)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/scripts.py:273:                    logger.debug('Able to replace executable using '
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/scripts.py:324:            logger.debug('not copying %s (up-to-date)', script)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:331:                logger.debug('Wrote %s to %s in wheel', p, ap)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:399:                assert distinfo, '.dist-info directory expected, not found'
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:563:                        logger.debug('lib_only: skipping %s', u_arcname)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:619:                    logger.debug('lib_only: returning None')
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:767:            logger.debug('%s already in path', pathname)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:782:            logger.debug('%s not in path', pathname)
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:887:                logger.debug('Cannot update non-compliant (PEP-440) '
./venv/lib/python3.9/site-packages/pip/_vendor/distlib/wheel.py:894:                logger.debug('Version updated from %r to %r', version,
./venv/lib/python3.9/site-packages/pip/_vendor/pyparsing/core.py:1934:            assert expr.matches("100")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:103:                logger.debug("Ignoring unknown cache-control directive: %s", directive)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:113:                        logger.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:118:                    logger.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:132:        logger.debug('Looking up "%s" in the cache', cache_url)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:137:            logger.debug('Request header has "no-cache", cache bypassed')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:141:            logger.debug('Request header has "max_age" as 0, cache bypassed')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:147:            logger.debug("No cache entry available")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:170:            logger.debug(msg)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:178:                logger.debug("Purging cached response: no date or etag")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:180:            logger.debug("Ignoring cached response: no date")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:186:        logger.debug("Current age based on date: %i", current_age)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:200:            logger.debug("Freshness lifetime from max-age: %i", freshness_lifetime)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:208:                logger.debug("Freshness lifetime from expires: %i", freshness_lifetime)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:214:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:222:            logger.debug("Adjusted current age from min-fresh: %i", current_age)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:226:            logger.debug('The response is "fresh", returning cached response')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:227:            logger.debug("%i > %i", freshness_lifetime, current_age)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:232:            logger.debug('The cached response is "stale" with no etag, purging')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:264:            logger.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:292:        logger.debug('Updating cache with response from "%s"', cache_url)
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:298:            logger.debug('Response header has "no-store"')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:301:            logger.debug('Request header has "no-store"')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:303:            logger.debug('Purging existing cache entry to honor "no-store"')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:314:            logger.debug('Response header has "Vary: *"')
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:327:            logger.debug("etag object cached for {0} seconds".format(expires_time))
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:328:            logger.debug("Caching due to etag")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:338:            logger.debug("Caching permanent redirect")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:348:                logger.debug("Caching b/c date exists and max-age > 0")
./venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py:366:                    logger.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py:56:    assert urllib3_version != ['dev']  # Verify urllib3 isn't installed from git.
./venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py:66:    assert major == 1
./venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py:67:    assert minor >= 21
./venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py:68:    assert minor <= 26
./venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py:75:        assert (3, 0, 2) <= (major, minor, patch) < (5, 0, 0)
./venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py:80:        assert (2, 0, 0) <= (major, minor, patch) < (3, 0, 0)
./venv/lib/python3.9/site-packages/pip/_vendor/requests/_internal_utils.py:37:    assert isinstance(u_string, str)
./venv/lib/python3.9/site-packages/pip/_vendor/requests/adapters.py:446:                    assert_same_host=False,
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/sanitizer.py:831:                assert attr in attrs
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/sanitizer.py:874:            assert token_type in ("StartTag", "EmptyTag")
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:36:                assert namespace is None or isinstance(namespace, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:37:                assert namespace != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:38:                assert isinstance(name, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:39:                assert name != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:40:                assert isinstance(token["data"], dict)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:42:                    assert type == "EmptyTag"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:44:                    assert type == "StartTag"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:48:                    assert namespace is None or isinstance(namespace, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:49:                    assert namespace != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:50:                    assert isinstance(name, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:51:                    assert name != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:52:                    assert isinstance(value, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:57:                assert namespace is None or isinstance(namespace, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:58:                assert namespace != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:59:                assert isinstance(name, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:60:                assert name != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:62:                    assert False, "Void element reported as EndTag token: %(tag)s" % {"tag": name}
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:65:                    assert start == (namespace, name)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:69:                assert isinstance(data, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:73:                assert isinstance(data, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:74:                assert data != ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:76:                    assert data.strip(spaceCharacters) == ""
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:80:                assert name is None or isinstance(name, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:81:                assert token["publicId"] is None or isinstance(name, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:82:                assert token["systemId"] is None or isinstance(name, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:85:                assert isinstance(token["name"], text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:88:                assert isinstance(token["data"], text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/filters/lint.py:91:                assert False, "Unknown token type: %(type)s" % {"type": type}
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree_lxml.py:142:            assert key in ("text", "tail"), "Text nodes are text or tail, found %s" % key
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree_lxml.py:181:        assert not isinstance(node, tuple), "Text nodes have no children"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree_lxml.py:183:        assert len(node) or node.text, "Node has no children"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree_lxml.py:192:            assert key in ("text", "tail"), "Text nodes are text or tail, found %s" % key
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree_lxml.py:208:            assert key in ("text", "tail"), "Text nodes are text or tail, found %s" % key
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/__init__.py:149:            assert False, "concatenateCharacterTokens should have got rid of all Space tokens"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree.py:54:                assert isinstance(node.tag, string_types), type(node.tag)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treewalkers/etree.py:125:                    assert list(parents[-1]).count(parent) == 1
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.py:92:                assert isinstance(element, str) or sys.version_info[0] == 2
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.py:104:            assert isinstance(element, etree._Element)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.py:327:        assert parent is None or parent is self.document
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.py:328:        assert self.document._elementTree is None
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/etree_lxml.py:344:            assert self.doctype.name
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/etree.py:225:                assert isinstance(element.tag, text_type), \
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/base.py:204:            assert isinstance(target, tuple)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/base.py:216:        assert False  # We should never reach this point
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treebuilders/base.py:325:        assert isinstance(name, text_type), "Element %s not unicode" % name
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:30:    assert invalid_unicode_no_surrogate[-1] == "]" and invalid_unicode_no_surrogate.count("]") == 1
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:71:        assert pos <= self._bufferedBytes()
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:104:            assert remainingBytes > 0
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:327:                    assert(ord(c) < 128)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:375:                assert self.chunk[self.chunkOffset] == char
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:423:        assert self.charEncoding[0] is not None
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:494:                    assert isinstance(buffer, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:514:        assert self.charEncoding[1] != "certain"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:520:            assert newEncoding is not None
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:541:        assert isinstance(string, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:567:        assert isinstance(buffer, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:583:        assert isinstance(value, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:793:        assert c is None or len(c) == 1
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_inputstream.py:866:        assert isinstance(data, bytes)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_ihatexml.py:117:            assert len(item) == 1
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_ihatexml.py:127:        assert item[1] >= item[0]
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:260:                assert self.phase not in phases
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:360:                assert self.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:366:                assert self.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:382:        assert contentType in ("RAWTEXT", "RCDATA")
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:780:            assert node.name == "head", "Expected head got %s" % node.name
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:847:            assert node.name == "noscript", "Expected noscript got %s" % node.name
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:968:            assert len(matchingElements) <= 3
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1020:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1030:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1679:            assert False, "Tried to process start tag %s in RCDATA/RAWTEXT mode" % token['name']
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1683:            assert node.name == "script"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1716:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1809:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1878:    #        assert False
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1929:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1969:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:1997:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2036:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2070:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2095:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2169:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2236:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2295:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2325:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2362:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2525:                        assert self.tree.openElements
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/html5parser.py:2592:                assert self.parser.innerHTML
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/treeadapters/sax.py:46:            assert False, "Unknown token type"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/serializer.py:225:        assert(isinstance(string, text_type))
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/serializer.py:232:        assert(isinstance(string, text_type))
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_tokenizer.py:1716:                assert char == ">"
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_utils.py:37:        assert isinstance(_x, text_type)
./venv/lib/python3.9/site-packages/pip/_vendor/html5lib/_utils.py:66:        assert len(self) == len(_dictEntries)
./venv/lib/python3.9/site-packages/pip/_vendor/rich/logging.py:127:            assert exc_type is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/logging.py:128:            assert exc_value is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/logging.py:236:    log.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/rich/logging.py:246:    log.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/rich/logging.py:258:        log.debug("in divide")
./venv/lib/python3.9/site-packages/pip/_vendor/rich/console.py:1091:        assert count >= 0, "count must be >= 0"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/console.py:1817:            assert frame is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/console.py:2016:        assert (
./venv/lib/python3.9/site-packages/pip/_vendor/rich/console.py:2072:        assert (
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:330:            assert self.triplet is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:333:            assert self.number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:336:            assert self.number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:339:            assert self.number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:342:            assert self.number is None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:458:            assert number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:464:            assert number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:469:            assert self.number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:473:            assert self.triplet is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:485:            assert self.triplet is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:507:                assert self.triplet is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:510:                assert self.number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:518:                assert self.triplet is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:521:                assert self.number is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py:534:    assert len(hex_color) == 6, "must be 6 characters"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/traceback.py:243:                assert (
./venv/lib/python3.9/site-packages/pip/_vendor/rich/traceback.py:580:                assert exclude_frames is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/_pick.py:13:    assert values, "1 or more values required"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/_ratio.py:129:    assert total_ratio > 0, "Sum of ratios must be > 0"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/pretty.py:172:    assert console is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/pretty.py:177:            assert console is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/pretty.py:472:        assert self.node is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/pretty.py:478:        assert node is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/pretty.py:480:        assert node.children
./venv/lib/python3.9/site-packages/pip/_vendor/rich/text.py:762:        assert tab_size is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/text.py:831:        assert len(character) == 1, "Character must be a string of length 1"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/text.py:848:        assert len(character) == 1, "Character must be a string of length 1"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/text.py:864:        assert len(character) == 1, "Character must be a string of length 1"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/text.py:999:        assert separator, "separator must not be empty"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/live.py:65:        assert refresh_per_second > 0, "refresh_per_second must be > 0"
./venv/lib/python3.9/site-packages/pip/_vendor/rich/syntax.py:409:                    assert lexer
./venv/lib/python3.9/site-packages/pip/_vendor/rich/prompt.py:214:        assert self.choices is not None
./venv/lib/python3.9/site-packages/pip/_vendor/rich/progress.py:587:        assert (
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/ssltransport.py:120:        assert reading or writing
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/ssltransport.py:142:            assert writing
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/__init__.py:15:    assert_fingerprint,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/retry.py:351:        log.debug("Converted retries value: %r -> %r", retries, new_retries)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/retry.py:594:        log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/__init__.py:60:    logger.debug("Added a stderr logging handler to logger: %s", __name__)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/securetransport.py:719:            assert leaf
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/securetransport.py:723:            assert certdata
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/securetransport.py:902:        assert not server_side
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/securetransport.py:903:        assert do_handshake_on_connect
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/securetransport.py:904:        assert suppress_ragged_eofs
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/appengine.py:213:                log.debug("Redirecting %s -> %s", url, redirect_location)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/appengine.py:230:            log.debug("Retry: %s", url)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:52:        log.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:69:        log.debug("Request headers: %s", headers)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:73:        log.debug("Response status: %s %s", res.status, res.reason)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:74:        log.debug("Response headers: %s", reshdr)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:75:        log.debug("Response data: %s [...]", res.read(100))
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:100:        log.debug("Request headers: %s", headers)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:103:        log.debug("Response status: %s %s", res.status, res.reason)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:104:        log.debug("Response headers: %s", dict(res.getheaders()))
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:105:        log.debug("Response data: %s [...]", res.read()[:100])
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:112:        log.debug("Connection established")
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py:123:        assert_same_host=True,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:56:    assert_fingerprint,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:294:    assert_fingerprint = None
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:330:        assert_hostname=None,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:331:        assert_fingerprint=None,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:447:            assert_fingerprint(
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:539:        asserted_hostname = stripped_hostname
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py:546:            asserted_hostname,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/backports/makefile.py:23:    assert reading or writing
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/backports/makefile.py:45:        assert writing
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:228:        log.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:273:            log.debug("Resetting dropped connection: %s", self.host)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:456:        log.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:469:            assert_header_parsing(httplib_response.msg)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:530:        assert_same_host=True,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:820:                assert_same_host,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:845:            log.debug("Redirecting %s -> %s", url, redirect_location)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:853:                assert_same_host=assert_same_host,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:875:            log.debug("Retry: %s", url)
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:883:                assert_same_host=assert_same_host,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:930:        assert_hostname=None,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:931:        assert_fingerprint=None,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:975:                assert_hostname=self.assert_hostname,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:976:                assert_fingerprint=self.assert_fingerprint,
./venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py:1001:        log.debug(
./venv/lib/python3.9/site-packages/pip/_vendor/distro.py:631:            assert obj is not None, "call {} on an instance".format(self._fname)
./venv/lib/python3.9/site-packages/pip/_vendor/typing_extensions.py:473:    assert isinstance(cls, GenericMeta)
./venv/lib/python3.9/site-packages/pip/_vendor/typing_extensions.py:715:            assert extra is None  # Protocols should not have extra
./venv/lib/python3.9/site-packages/pip/_vendor/typing_extensions.py:717:                assert origin is not None
./venv/lib/python3.9/site-packages/pip/_vendor/typing_extensions.py:718:                assert all(isinstance(t, typing.TypeVar) for t in tvars), tvars
./venv/lib/python3.9/site-packages/pip/_vendor/typing_extensions.py:1111:            assert Point2D(x=1, y=2, label='first') == dict(x=1, y=2, label='first')
./venv/lib/python3.9/site-packages/pip/_vendor/typing_extensions.py:1150:            assert len(params) == 1
./venv/lib/python3.9/site-packages/smmap/mman.py:355:            assert len(a) == 1
./venv/lib/python3.9/site-packages/smmap/mman.py:379:        assert r.includes_ofs(offset)
./venv/lib/python3.9/site-packages/smmap/buf.py:56:        assert c.is_valid()
./venv/lib/python3.9/site-packages/smmap/buf.py:68:        assert c.is_valid()
./venv/lib/python3.9/site-packages/smmap/buf.py:86:                assert c.is_valid()
./venv/lib/python3.9/site-packages/smmap/util.py:176:        assert self._uc > -1, "Increments must match decrements, usage counter negative: %i" % self._uc
./venv/lib/python3.9/site-packages/setuptools/package_index.py:319:                self.debug("Found link: %s", url)
./venv/lib/python3.9/site-packages/setuptools/package_index.py:372:            self.debug("Found: %s", fn)
./venv/lib/python3.9/site-packages/setuptools/package_index.py:497:            self.debug("%s does not match %s", requirement, dist)
./venv/lib/python3.9/site-packages/setuptools/package_index.py:914:        log.debug(msg, *args)
./venv/lib/python3.9/site-packages/setuptools/_vendor/packaging/tags.py:115:        logger.debug(
./venv/lib/python3.9/site-packages/setuptools/_vendor/packaging/_musllinux.py:130:    assert plat.startswith("linux-"), "not linux"
./venv/lib/python3.9/site-packages/setuptools/_vendor/packaging/markers.py:152:    assert isinstance(marker, (list, tuple, str))
./venv/lib/python3.9/site-packages/setuptools/_vendor/packaging/markers.py:226:        assert isinstance(marker, (list, tuple, str))
./venv/lib/python3.9/site-packages/setuptools/_vendor/packaging/markers.py:242:            assert marker in ["and", "or"]
./venv/lib/python3.9/site-packages/setuptools/_vendor/packaging/_manylinux.py:146:        assert version_string is not None
./venv/lib/python3.9/site-packages/setuptools/_vendor/pyparsing.py:2224:            assert expr.matches("100")
./venv/lib/python3.9/site-packages/setuptools/_vendor/typing_extensions.py:473:    assert isinstance(cls, GenericMeta)
./venv/lib/python3.9/site-packages/setuptools/_vendor/typing_extensions.py:715:            assert extra is None  # Protocols should not have extra
./venv/lib/python3.9/site-packages/setuptools/_vendor/typing_extensions.py:717:                assert origin is not None
./venv/lib/python3.9/site-packages/setuptools/_vendor/typing_extensions.py:718:                assert all(isinstance(t, typing.TypeVar) for t in tvars), tvars
./venv/lib/python3.9/site-packages/setuptools/_vendor/typing_extensions.py:1111:            assert Point2D(x=1, y=2, label='first') == dict(x=1, y=2, label='first')
./venv/lib/python3.9/site-packages/setuptools/_vendor/typing_extensions.py:1150:            assert len(params) == 1
./venv/lib/python3.9/site-packages/setuptools/discovery.py:354:        log.debug(
./venv/lib/python3.9/site-packages/setuptools/discovery.py:375:        log.debug(f"`explicit-layout` detected -- analysing {package_dir}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:381:        log.debug(f"discovered packages -- {self.dist.packages}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:400:        log.debug(f"`src-layout` detected -- analysing {src_dir}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:405:        log.debug(f"discovered packages -- {self.dist.packages}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:406:        log.debug(f"discovered py_modules -- {self.dist.py_modules}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:419:        log.debug(f"`flat-layout` detected -- analysing {self._root_dir}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:425:        log.debug(f"discovered packages -- {self.dist.packages}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:431:        log.debug(f"discovered py_modules -- {self.dist.py_modules}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:465:        log.debug("No `name` configuration, performing automatic discovery")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:480:                log.debug(f"Single module/package detected, name: {items[0]}")
./venv/lib/python3.9/site-packages/setuptools/discovery.py:495:            log.debug(f"Common parent package detected, name: {parent_pkg}")
./venv/lib/python3.9/site-packages/setuptools/config/_validate_pyproject/formats.py:153:            _logger.debug(msg)
./venv/lib/python3.9/site-packages/setuptools/config/_validate_pyproject/formats.py:161:            _logger.debug(msg)
./venv/lib/python3.9/site-packages/setuptools/config/_validate_pyproject/formats.py:166:                _logger.debug("Problem with download, skipping validation")
./venv/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:41:        _logger.debug(ex.details)  # type: ignore
./venv/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:128:            _logger.debug(f"ignored error: {ex.__class__.__name__} - {ex}")
./venv/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:378:        _logger.debug(f"ignored error: {ex.__class__.__name__} - {ex}")
./venv/lib/python3.9/site-packages/setuptools/installer.py:19:    assert isinstance(find_links, (tuple, list))
./venv/lib/python3.9/site-packages/setuptools/glob.py:44:        assert not s
./venv/lib/python3.9/site-packages/setuptools/glob.py:114:    assert _isrecursive(pattern)
./venv/lib/python3.9/site-packages/setuptools/build_meta.py:204:            assert len(dist_infos) == 1
./venv/lib/python3.9/site-packages/setuptools/command/bdist_egg.py:242:                    log.debug("Deleting %s", path)
./venv/lib/python3.9/site-packages/setuptools/command/bdist_egg.py:446:                log.debug("adding '%s'", p)
./venv/lib/python3.9/site-packages/setuptools/command/build_ext.py:318:        assert output_dir is None  # distutils build_ext doesn't pass this
./venv/lib/python3.9/site-packages/setuptools/command/easy_install.py:1068:        assert wheel.is_compatible()
./venv/lib/python3.9/site-packages/setuptools/command/easy_install.py:1254:        log.debug("Unpacking %s to %s", src, dst)
./venv/lib/python3.9/site-packages/setuptools/command/easy_install.py:1623:            log.debug("Saving %s", self.filename)
./venv/lib/python3.9/site-packages/setuptools/command/easy_install.py:1633:            log.debug("Deleting empty %s", self.filename)
./venv/lib/python3.9/site-packages/setuptools/command/easy_install.py:1953:    log.debug("changing mode of %s to %o", path, mode)
./venv/lib/python3.9/site-packages/setuptools/command/easy_install.py:1957:        log.debug("chmod failed: %s", e)
./venv/lib/python3.9/site-packages/setuptools/command/install_lib.py:91:        assert preserve_mode and preserve_times and not preserve_symlinks
./venv/lib/python3.9/site-packages/setuptools/command/upload_docs.py:176:        assert not params and not query and not fragments
./venv/lib/python3.9/site-packages/setuptools/command/install_egg_info.py:60:            log.debug("Copying %s to %s", src, dst)
./venv/lib/python3.9/site-packages/setuptools/command/setopt.py:40:    log.debug("Reading configuration from %s", filename)
./venv/lib/python3.9/site-packages/setuptools/command/setopt.py:50:                log.debug("Adding new section [%s] to %s", section, filename)
./venv/lib/python3.9/site-packages/setuptools/command/setopt.py:54:                    log.debug(
./venv/lib/python3.9/site-packages/setuptools/command/setopt.py:64:                    log.debug(
./venv/lib/python3.9/site-packages/setuptools/dist.py:234:        assert not ep.extras
./venv/lib/python3.9/site-packages/setuptools/dist.py:246:        assert isinstance(value, (list, tuple))
./venv/lib/python3.9/site-packages/setuptools/dist.py:248:        assert ''.join(value) != value
./venv/lib/python3.9/site-packages/setuptools/dist.py:258:    assert_string_list(dist, attr, ns_packages)
./venv/lib/python3.9/site-packages/setuptools/dist.py:358:        assert_string_list(dist, 'values of {!r} dict'.format(attr), v)
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:40:        log.debug("Visual C++ is not registered")
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:107:        log.debug("No suitable Visual C++ version found")
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:112:        log.debug("%s cannot be found", vcvarsall)
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:213:        assert not self.initialized, "don't init multiple times"
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:430:                log.debug('Executing "%s" %s', self.lib, ' '.join(lib_args))
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:435:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:500:                log.debug('Executing "%s" %s', self.linker, ' '.join(ld_args))
./venv/lib/python3.9/site-packages/setuptools/_distutils/_msvccompiler.py:505:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py:202:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py:253:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/filelist.py:337:        assert pattern_re.startswith(start) and pattern_re.endswith(end)
./venv/lib/python3.9/site-packages/setuptools/_distutils/filelist.py:343:        assert prefix_re.startswith(start) and prefix_re.endswith(end)
./venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py:339:        assert len(objects) == len(sources)
./venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py:404:        assert len(objects) == len(sources)
./venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py:872:        assert output_dir is not None
./venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py:878:        assert output_dir is not None
./venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py:885:        assert output_dir is not None
./venv/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py:903:        log.debug(msg)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:228:        log.debug("Unable to find productdir in registry")
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:239:                log.debug("%s is not a valid directory" % productdir)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:242:            log.debug("Env var %s is not set or invalid" % toolskey)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:244:        log.debug("No productdir found")
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:249:    log.debug("Unable to find vcvarsall.bat")
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:261:    log.debug("Calling 'vcvarsall.bat %s' (version=%s)", arch, version)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:339:        assert not self.initialized, "don't init multiple times"
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:562:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvc9compiler.py:658:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/archive_util.py:226:        log.debug("changing into '%s'", root_dir)
./venv/lib/python3.9/site-packages/setuptools/_distutils/archive_util.py:253:            log.debug("changing back to '%s'", save_cwd)
./venv/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:403:            log.debug(skip_msg)
./venv/lib/python3.9/site-packages/setuptools/_distutils/version.py:221:            assert False, "never get here"
./venv/lib/python3.9/site-packages/setuptools/_distutils/util.py:485:                    log.debug("skipping byte-compilation of %s to %s",
./venv/lib/python3.9/site-packages/setuptools/_distutils/fancy_getopt.py:111:        assert isinstance(aliases, dict)
./venv/lib/python3.9/site-packages/setuptools/_distutils/fancy_getopt.py:241:                assert len(opt) > 2 and opt[:2] == '--'
./venv/lib/python3.9/site-packages/setuptools/_distutils/fancy_getopt.py:249:                assert val == '', "boolean option can't have value"
./venv/lib/python3.9/site-packages/setuptools/_distutils/file_util.py:115:            log.debug("not copying %s (output up-to-date)", src)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvccompiler.py:450:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvccompiler.py:529:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/msvccompiler.py:639:    log.debug("Importing new compiler from distutils.msvc9compiler")
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py:498:            log.debug("skipping '%s' extension (up-to-date)", ext.name)
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/clean.py:55:            log.debug("'%s' does not exist -- can't clean it",
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/bdist_wininst.py:154:                assert self.skip_build, "Should have already checked this"
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/bdist_wininst.py:198:        log.debug("removing temporary file '%s'", arcname)
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_py.py:63:                assert 0 <= self.optimize <= 2
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_py.py:371:                assert package == package_
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/build_scripts.py:83:            log.debug("not copying %s (up-to-date)", script)
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/bdist_rpm.py:349:                assert(len(l) == 2)
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/bdist_rpm.py:372:                assert(os.path.exists(srpm))
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/install.py:499:        log.debug(msg + ":")
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/install.py:511:            log.debug("  %s: %s", opt_name, val)
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/install.py:705:            log.debug(("modules installed to '%s', which is not in "
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/bdist_msi.py:209:                assert self.skip_build, "Should have already checked this"
./venv/lib/python3.9/site-packages/setuptools/_distutils/command/bdist_msi.py:383:            assert start < 500
./venv/lib/python3.9/site-packages/setuptools/_distutils/bcppcompiler.py:166:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/_distutils/bcppcompiler.py:301:            log.debug("skipping %s (up-to-date)", output_filename)
./venv/lib/python3.9/site-packages/setuptools/wheel.py:49:        assert not filenames
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/tags.py:115:        logger.debug(
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_musllinux.py:130:    assert plat.startswith("linux-"), "not linux"
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/markers.py:152:    assert isinstance(marker, (list, tuple, str))
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/markers.py:226:        assert isinstance(marker, (list, tuple, str))
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/markers.py:242:            assert marker in ["and", "or"]
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_manylinux.py:146:        assert version_string is not None
./venv/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing.py:2224:            assert expr.matches("100")
./venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:59:    assert '_distutils' in core.__file__, core.__file__
./venv/lib/python3.9/site-packages/_distutils_hack/__init__.py:60:    assert 'setuptools._distutils.log' not in sys.modules
./venv/lib/python3.9/site-packages/gitdb/pack.py:237:        assert(len(pack_sha) == 20)
./venv/lib/python3.9/site-packages/gitdb/pack.py:291:                assert version_id == self._version, "Unsupported index version: %i" % version_id
./venv/lib/python3.9/site-packages/gitdb/pack.py:454:        assert isinstance(partial_bin_sha, bytes), "partial_bin_sha must be bytes"
./venv/lib/python3.9/site-packages/gitdb/pack.py:557:            assert ostream.stream._br == ostream.size
./venv/lib/python3.9/site-packages/gitdb/pack.py:684:        assert offsets_sorted, "Cannot handle empty indices"
./venv/lib/python3.9/site-packages/gitdb/pack.py:848:            assert shawriter.sha(as_hex=False) == sha
./venv/lib/python3.9/site-packages/gitdb/pack.py:977:            assert(br == obj.size)
./venv/lib/python3.9/site-packages/gitdb/pack.py:995:        assert len(pack_sha) == 20
./venv/lib/python3.9/site-packages/gitdb/fun.py:297:            assert self[-1].rbound() == target_size
./venv/lib/python3.9/site-packages/gitdb/fun.py:298:            assert reduce(lambda x, y: x + y, (d.ts for d in self), 0) == target_size
./venv/lib/python3.9/site-packages/gitdb/fun.py:306:            assert dc.ts > 0
./venv/lib/python3.9/site-packages/gitdb/fun.py:308:                assert len(dc.data) >= dc.ts
./venv/lib/python3.9/site-packages/gitdb/fun.py:317:            assert lft.rbound() == rgt.to
./venv/lib/python3.9/site-packages/gitdb/fun.py:318:            assert lft.to + lft.ts == rgt.to
./venv/lib/python3.9/site-packages/gitdb/fun.py:678:    assert i == delta_buf_size, "delta replay has gone wild"
./venv/lib/python3.9/site-packages/gitdb/stream.py:86:        assert attr == '_s'
./venv/lib/python3.9/site-packages/gitdb/stream.py:364:        assert len(stream_list) > 1, "Need at least one delta and one base stream"
./venv/lib/python3.9/site-packages/gitdb/db/pack.py:169:            assert del_index != -1
./venv/lib/python3.9/site-packages/gitdb/db/git.py:66:            assert loose_db is not None and hasattr(loose_db, 'store'), "First database needs store functionality"
./venv/lib/python3.9/site-packages/gitdb/base.py:28:        assert dbi[0] == dbi.binsha
./venv/lib/python3.9/site-packages/gitdb/base.py:29:        assert dbi[1] == dbi.type
./venv/lib/python3.9/site-packages/gitdb/base.py:30:        assert dbi[2] == dbi.size
./venv/lib/python3.9/site-packages/git/cmd.py:110:                        assert isinstance(line, bytes)
./venv/lib/python3.9/site-packages/git/cmd.py:501:                log.debug('AutoInterrupt wait stderr: %r' % (errstr,))
./venv/lib/python3.9/site-packages/git/cmd.py:870:        log.debug("Popen(%s, cwd=%s, universal_newlines=%s, shell=%s, istream=%s)",
./venv/lib/python3.9/site-packages/git/config.py:239:        assert_never(config_level,                    # type: ignore[unreachable]
./venv/lib/python3.9/site-packages/git/config.py:595:                        assert osp.isabs(file_path), "Need absolute paths to be sure our cycle checks will work"
./venv/lib/python3.9/site-packages/git/config.py:675:            log.debug("Skipping write-back of configuration file as include files were merged in." +
./venv/lib/python3.9/site-packages/git/remote.py:596:            assert isinstance(remote_details, str)
./venv/lib/python3.9/site-packages/git/remote.py:608:                    assert isinstance(remote_details, str)
./venv/lib/python3.9/site-packages/git/remote.py:616:                        assert isinstance(remote_details, str)
./venv/lib/python3.9/site-packages/git/remote.py:773:            log.debug(msg)
./venv/lib/python3.9/site-packages/git/remote.py:774:            log.debug(b"info lines: " + str(fetch_info_lines).encode("UTF-8"))
./venv/lib/python3.9/site-packages/git/remote.py:775:            log.debug(b"head info: " + str(fetch_head_info).encode("UTF-8"))
./venv/lib/python3.9/site-packages/git/remote.py:787:                log.debug("Caught error while parsing line: %s", exc)
./venv/lib/python3.9/site-packages/git/util.py:372:            log.debug('Failed checking if running in CYGWIN due to: %r', ex)
./venv/lib/python3.9/site-packages/git/util.py:1005:        assert isinstance(index, (int, str, slice)), "Index of IterableList should be an int or str"
./venv/lib/python3.9/site-packages/git/util.py:1020:        assert isinstance(index, (int, str)), "Index of IterableList should be an int or str"
./venv/lib/python3.9/site-packages/git/objects/tree.py:171:        assert isinstance(binsha, bytes) and isinstance(mode, int) and isinstance(name, str)
./venv/lib/python3.9/site-packages/git/objects/submodule/util.py:86:        assert self._smref is not None
./venv/lib/python3.9/site-packages/git/objects/submodule/util.py:88:        assert not isinstance(self._file_or_files, BytesIO)
./venv/lib/python3.9/site-packages/git/objects/submodule/root.py:211:                                assert nn not in [r.name for r in rmts]
./venv/lib/python3.9/site-packages/git/objects/submodule/base.py:214:            assert parent_commit is not None, "need valid parent_commit in bare repositories"
./venv/lib/python3.9/site-packages/git/objects/submodule/base.py:661:                            log.debug(msg)
./venv/lib/python3.9/site-packages/git/objects/submodule/base.py:888:                    assert method
./venv/lib/python3.9/site-packages/git/objects/util.py:234:            assert splitter > -1
./venv/lib/python3.9/site-packages/git/objects/util.py:566:        assert is_commit_traversed(ret_tup), f"{[type(x) for x in list(ret_tup[0])]}"
./venv/lib/python3.9/site-packages/git/objects/commit.py:133:            assert isinstance(tree, Tree), "Tree needs to be a Tree instance, was %s" % type(tree)
./venv/lib/python3.9/site-packages/git/objects/commit.py:400:            assert len(hexsha) == 40, "Invalid line: %s" % hexsha
./venv/lib/python3.9/site-packages/git/objects/base.py:60:        assert len(binsha) == 20, "Require 20 byte binary sha, got %r, len = %i" % (binsha, len(binsha))
./venv/lib/python3.9/site-packages/git/refs/log.py:206:            assert isinstance(_stream, mmap)
./venv/lib/python3.9/site-packages/git/refs/symbolic.py:170:            assert(len(tokens) != 0)
./venv/lib/python3.9/site-packages/git/index/fun.py:171:        assert plen == len(path), "Path %s too long to fit into index" % entry.path
./venv/lib/python3.9/site-packages/git/index/fun.py:197:    assert version in (1, 2)
./venv/lib/python3.9/site-packages/git/index/fun.py:210:        assert isinstance(entry_first, BaseIndexEntry)
./venv/lib/python3.9/site-packages/git/index/fun.py:256:    assert len(extension_data) > 19, "Index Footer was not at least a sha on content as it was only %i bytes in size"\
./venv/lib/python3.9/site-packages/git/index/fun.py:405:                assert theirs is not None
./venv/lib/python3.9/site-packages/git/index/base.py:655:        assert len(entries_added) == 0
./venv/lib/python3.9/site-packages/git/index/base.py:949:            assert len(tokens) == 2, "Too many tokens in %s" % mvlines[ln]
./venv/lib/python3.9/site-packages/git/diff.py:67:        assert path.startswith(b'a/') or path.startswith(b'b/')
./venv/lib/python3.9/site-packages/git/diff.py:298:        assert a_rawpath is None or isinstance(a_rawpath, bytes)
./venv/lib/python3.9/site-packages/git/diff.py:299:        assert b_rawpath is None or isinstance(b_rawpath, bytes)
./venv/lib/python3.9/site-packages/git/diff.py:332:        assert raw_rename_from is None or isinstance(raw_rename_from, bytes)
./venv/lib/python3.9/site-packages/git/diff.py:333:        assert raw_rename_to is None or isinstance(raw_rename_to, bytes)
./venv/lib/python3.9/site-packages/git/repo/fun.py:233:            assert obj is not None
./venv/lib/python3.9/site-packages/git/repo/fun.py:269:                assert ref is not None, "Requre Reference to access reflog"
./venv/lib/python3.9/site-packages/git/repo/base.py:485:            assert_never(config_level,                                                  # type:ignore[unreachable]
./venv/lib/python3.9/site-packages/git/repo/base.py:641:                    log.debug("Commit hash points to an object of type '%s'. Requested were objects of type '%s'",
./venv/lib/python3.9/site-packages/git/repo/base.py:647:            log.debug("Commit hash is invalid.")
./venv/lib/python3.9/site-packages/git/repo/base.py:1085:            log.debug("Cmd(%s)'s unused stdout: %s", cmdline, stdout)
./venv/lib/python3.9/site-packages/pydriller/git.py:73:        assert self._repo
./venv/lib/python3.9/site-packages/pydriller/git.py:197:            logger.debug(f"Tag {tag} not found")
./venv/lib/python3.9/site-packages/pydriller/git.py:275:                logger.debug(f"Could not found file {mod.filename} in commit {commit.hash}. Probably a double rename!")
./venv/lib/python3.9/site-packages/pydriller/git.py:318:            logger.debug(f"Could not find information of file {path}")
./venv/lib/python3.9/site-packages/pydriller/utils/conf.py:268:                logger.debug('Commit filtered for modification types')
./venv/lib/python3.9/site-packages/pydriller/utils/conf.py:271:            logger.debug("Commit filtered because it is not one of the specified commits")
./venv/lib/python3.9/site-packages/pydriller/utils/conf.py:274:            logger.debug("Commit filtered because it did not modify the specified file")
./venv/lib/python3.9/site-packages/pydriller/utils/conf.py:277:            logger.debug("Commit filtered because it is not tagged")
./venv/lib/python3.9/site-packages/pydriller/repository.py:199:            assert self._tmp_dir is not None
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:143:        assert dmm_prop is DMMProperty.UNIT_INTERFACING
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:249:            assert self._old_path
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:428:        assert self.language_supported
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:669:        assert self._modified_files is not None
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:729:            logger.debug(
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:739:            logger.debug(
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:764:        assert self._branches is not None
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:895:        assert good_change >= 0 and bad_change >= 0
./venv/lib/python3.9/site-packages/pydriller/domain/commit.py:902:            assert 0.0 <= proportion <= 1.0
./versioneer.py:380:    assert isinstance(commands, list)
./versioneer.py:484:    assert isinstance(commands, list)
./versioneer.py:1414:    assert cfg.VCS is not None, "please set [versioneer]VCS= in setup.cfg"
./versioneer.py:1416:    assert handlers, "unrecognized VCS '%s'" % cfg.VCS
./versioneer.py:1418:    assert cfg.versionfile_source is not None, \
./versioneer.py:1420:    assert cfg.tag_prefix is not None, "please set versioneer.tag_prefix"
